import { useCallback, useEffect, useState } from 'react'
import type { Session } from '@supabase/supabase-js'
import { localDate } from '../lib/store'
import { canAddMindNode, descendantIds } from '../lib/mindMap'
import { createDemoTeamState, loadDemoTeamState, saveDemoTeamState, saveDemoUser } from '../lib/teamStore'
import { supabase as maybeSupabase, supabaseConfigured } from '../lib/supabase'
import type { HabitPlan, TeamGoal, TeamIdea, TeamMindNode, TeamProfile, TeamProject, TeamState, TeamSubtask, TeamTask, WorkspaceMember } from '../types/team'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Row = Record<string, any>
const uid = () => crypto.randomUUID()
const supabase = maybeSupabase!
const mapProfile = (r: Row): TeamProfile => ({ id: r.id, displayName: r.display_name, avatarColor: r.avatar_color, workspaceXp: r.workspace_xp, trophies: r.trophies })
const mapMember = (r: Row): WorkspaceMember => ({ workspaceId: r.workspace_id, userId: r.user_id, role: r.role, joinedAt: r.joined_at?.slice(0, 10) })
const mapProject = (r: Row): TeamProject => ({ id: r.id, workspaceId: r.workspace_id, name: r.name, summary: r.summary ?? '', color: r.color, status: r.status, priority: r.priority ?? 'normal', sortOrder: r.sort_order ?? 0 })
const mapGoal = (r: Row): TeamGoal => ({ id: r.id, workspaceId: r.workspace_id, title: r.title, description: r.description ?? '', projectId: r.project_id ?? undefined, dependsOnGoalId: r.depends_on_goal_id ?? undefined, ownerId: r.owner_id ?? undefined, metric: r.metric, target: r.target, current: r.current, deadline: r.deadline ?? undefined, rewardXp: r.reward_xp, completed: r.completed, status: r.status ?? (r.completed ? 'concluida' : 'planejada'), priority: r.priority ?? 'normal', sortOrder: r.sort_order ?? 0 })
const mapTask = (r: Row): TeamTask => ({ id: r.id, workspaceId: r.workspace_id, projectId: r.project_id ?? undefined, goalId: r.goal_id ?? undefined, dependsOnTaskId: r.depends_on_task_id ?? undefined, title: r.title, description: r.description ?? '', area: r.area, assigneeId: r.assignee_id ?? undefined, status: r.status, priority: r.priority, points: r.points, dueDate: r.due_date ?? undefined, waitingUntil: r.waiting_until ?? undefined, createdBy: r.created_by, completedAt: r.completed_at ?? undefined, sortOrder: r.sort_order ?? 0 })
const mapSubtask = (r: Row): TeamSubtask => ({ id: r.id, workspaceId: r.workspace_id, taskId: r.task_id, title: r.title, completed: r.completed, sortOrder: r.sort_order ?? 0, completedAt: r.completed_at ?? undefined })
const mapIdea = (r: Row): TeamIdea => ({ id: r.id, workspaceId: r.workspace_id, title: r.title, notes: r.notes ?? '', status: r.status, priority: r.priority, createdBy: r.created_by, createdAt: r.created_at })
const mapMindNode = (r: Row): TeamMindNode => ({ id: r.id, workspaceId: r.workspace_id, goalId: r.goal_id, parentId: r.parent_id ?? undefined, title: r.title, note: r.note ?? '', sortOrder: r.sort_order ?? 0, createdBy: r.created_by })
const mapHabit = (r: Row): HabitPlan => ({ id: r.id, userId: r.user_id, workspaceId: r.workspace_id ?? undefined, kind: r.kind, mode: r.mode, baseline: r.baseline, target: r.target, unit: r.unit, shareWithWorkspace: r.share_with_workspace, startedAt: r.started_at })

export function useTeamState() {
  const [state, setState] = useState<TeamState>(loadDemoTeamState)
  const [session, setSession] = useState<Session | null>(null)
  const loadCloud = useCallback(async (userId: string, preferredWorkspace?: string | null) => {
    if (!supabase) return
    setState((current) => ({ ...current, mode: 'cloud', configured: true, loading: true, error: '' }))
    try {
      const [{ data: profileRows, error: profileError }, { data: memberRows, error: memberError }] = await Promise.all([supabase.from('profiles').select('*'), supabase.from('workspace_members').select('*')])
      if (profileError || memberError) throw profileError ?? memberError
      const memberships = (memberRows ?? []).map(mapMember); const workspaceIds = [...new Set(memberships.map((item) => item.workspaceId))]
      const workspaceResult = workspaceIds.length ? await supabase.from('workspaces').select('*').in('id', workspaceIds) : { data: [], error: null }
      if (workspaceResult.error) throw workspaceResult.error
      const activeWorkspaceId = preferredWorkspace && workspaceIds.includes(preferredWorkspace) ? preferredWorkspace : workspaceIds[0] ?? null
      const empty = Promise.resolve({ data: [], error: null }); const q = (table: string) => activeWorkspaceId ? supabase.from(table).select('*').eq('workspace_id', activeWorkspaceId) : empty
      const results = await Promise.all([q('workspace_projects'), q('workspace_tasks'), q('workspace_subtasks'), q('workspace_goals'), q('workspace_ideas'), q('workspace_mind_nodes'), q('workspace_activities'), supabase.from('habit_plans').select('*'), supabase.from('habit_logs').select('*').gte('date', new Date(Date.now() - 31 * 86400000).toISOString().slice(0, 10))])
      const firstError = results.find((item) => item.error)?.error; if (firstError) throw firstError
      const profiles = (profileRows ?? []).map(mapProfile)
      setState({ mode: 'cloud', configured: true, loading: false, error: '', user: profiles.find((item) => item.id === userId) ?? null, profiles,
        workspaces: (workspaceResult.data ?? []).map((r: Row) => ({ id: r.id, name: r.name, description: r.description ?? '', inviteCode: r.invite_code, createdBy: r.created_by })), activeWorkspaceId, members: memberships,
        projects: (results[0].data ?? []).map(mapProject), tasks: (results[1].data ?? []).map(mapTask), subtasks: (results[2].data ?? []).map(mapSubtask), goals: (results[3].data ?? []).map(mapGoal), ideas: (results[4].data ?? []).map(mapIdea), mindNodes: (results[5].data ?? []).map(mapMindNode),
        activities: (results[6].data ?? []).map((r: Row) => ({ id: r.id, workspaceId: r.workspace_id, userId: r.user_id, title: r.title, points: r.points, date: r.activity_date, type: r.type })), habitPlans: (results[7].data ?? []).map(mapHabit), habitLogs: (results[8].data ?? []).map((r: Row) => ({ id: r.id, planId: r.plan_id, userId: r.user_id, date: r.date, amount: r.amount, craving: r.craving ?? undefined, note: r.note ?? undefined })) })
    } catch (error) { setState((current) => ({ ...current, loading: false, error: error instanceof Error ? error.message : 'Não foi possível carregar o workspace.' })) }
  }, [])

  useEffect(() => { if (!supabaseConfigured || !supabase) return; supabase.auth.getSession().then(({ data }) => { setSession(data.session); if (data.session) loadCloud(data.session.user.id) }); const { data } = supabase.auth.onAuthStateChange((_event, next) => { setSession(next); if (next) loadCloud(next.user.id); else setState({ ...createDemoTeamState(), mode: 'cloud', configured: true, user: null, workspaces: [], members: [], projects: [], tasks: [], subtasks: [], goals: [], ideas: [], mindNodes: [], activities: [], habitPlans: [], habitLogs: [] }) }); return () => data.subscription.unsubscribe() }, [loadCloud])
  useEffect(() => { if (state.mode === 'demo') saveDemoTeamState(state) }, [state])
  useEffect(() => { if (!supabase || !session || !state.activeWorkspaceId) return; const client = supabase; const reload = () => loadCloud(session.user.id, state.activeWorkspaceId); const channel = client.channel(`workspace:${state.activeWorkspaceId}`); ['workspace_projects', 'workspace_tasks', 'workspace_subtasks', 'workspace_goals', 'workspace_ideas', 'workspace_mind_nodes', 'workspace_activities'].forEach((table) => channel.on('postgres_changes', { event: '*', schema: 'public', table, filter: `workspace_id=eq.${state.activeWorkspaceId}` }, reload)); channel.subscribe(); return () => { client.removeChannel(channel) } }, [session, state.activeWorkspaceId, loadCloud])

  const updateDemo = (change: (current: TeamState) => TeamState) => setState((current) => change(current))
  const refresh = async () => { if (session) await loadCloud(session.user.id, state.activeWorkspaceId) }
  async function cloud(action: () => PromiseLike<{ error: { message: string } | null }>) { const result = await action(); if (result.error) { setState((current) => ({ ...current, error: result.error!.message })); throw new Error(result.error.message) } await refresh() }
  async function signUp(email: string, password: string, displayName: string) { if (!supabase) return 'Supabase ainda não está configurado.'; const { error } = await supabase.auth.signUp({ email, password, options: { data: { display_name: displayName.trim() } } }); return error?.message ?? '' }
  async function signIn(email: string, password: string) { if (!supabase) return 'Supabase ainda não está configurado.'; const { error } = await supabase.auth.signInWithPassword({ email, password }); return error?.message ?? '' }
  async function signOut() { await supabase?.auth.signOut() }
  function switchDemoUser(userId: string) { saveDemoUser(userId); updateDemo((current) => ({ ...current, user: current.profiles.find((item) => item.id === userId) ?? current.user })) }
  async function createWorkspace(name: string) { if (!session || !supabase) return; await cloud(() => supabase.from('workspaces').insert({ name: name.trim(), description: 'Operação compartilhada', created_by: session.user.id })) }
  async function joinWorkspace(code: string) { if (!session || !supabase) return; await cloud(() => supabase.rpc('join_workspace_by_code', { join_code: code.trim().toUpperCase() })) }
  async function setWorkspace(id: string) { if (session) await loadCloud(session.user.id, id); else updateDemo((current) => ({ ...current, activeWorkspaceId: id })) }

  async function saveProject(input: Omit<TeamProject, 'id' | 'workspaceId' | 'sortOrder'>, id?: string) { if (!state.activeWorkspaceId) return; const data = { name: input.name.trim(), summary: input.summary.trim(), color: input.color, status: input.status, priority: input.priority }; if (state.mode === 'cloud' && supabase) return cloud(() => id ? supabase.from('workspace_projects').update(data).eq('id', id) : supabase.from('workspace_projects').insert({ ...data, workspace_id: state.activeWorkspaceId })); updateDemo((c) => ({ ...c, projects: id ? c.projects.map((p) => p.id === id ? { ...p, ...data } : p) : [...c.projects, { ...data, id: uid(), workspaceId: c.activeWorkspaceId!, sortOrder: c.projects.length }] })) }
  async function deleteProject(id: string) { if (state.mode === 'cloud' && supabase) return cloud(() => supabase.from('workspace_projects').delete().eq('id', id)); updateDemo((c) => ({ ...c, projects: c.projects.filter((p) => p.id !== id), goals: c.goals.map((g) => g.projectId === id ? { ...g, projectId: undefined } : g), tasks: c.tasks.map((t) => t.projectId === id ? { ...t, projectId: undefined } : t) })) }
  async function saveGoal(input: Omit<TeamGoal, 'id' | 'workspaceId' | 'current' | 'completed' | 'sortOrder'>, id?: string) { if (!state.activeWorkspaceId) return; const data = { title: input.title.trim(), description: input.description.trim(), project_id: input.projectId || null, depends_on_goal_id: input.dependsOnGoalId || null, owner_id: input.ownerId || null, metric: input.metric.trim(), target: Math.max(1, input.target), deadline: input.deadline || null, reward_xp: input.rewardXp, status: input.status, priority: input.priority }; if (state.mode === 'cloud' && supabase) return cloud(() => id ? supabase.from('workspace_goals').update(data).eq('id', id) : supabase.from('workspace_goals').insert({ ...data, workspace_id: state.activeWorkspaceId })); const local = { title: data.title, description: data.description, projectId: input.projectId, dependsOnGoalId: input.dependsOnGoalId, ownerId: input.ownerId, metric: data.metric, target: data.target, deadline: input.deadline, rewardXp: input.rewardXp, status: input.status, priority: input.priority }; updateDemo((c) => ({ ...c, goals: id ? c.goals.map((g) => g.id === id ? { ...g, ...local, completed: input.status === 'concluida' } : g) : [...c.goals, { ...local, id: uid(), workspaceId: c.activeWorkspaceId!, current: 0, completed: false, sortOrder: c.goals.length }] })) }
  async function deleteGoal(id: string) { if (state.mode === 'cloud' && supabase) return cloud(() => supabase.from('workspace_goals').delete().eq('id', id)); updateDemo((c) => ({ ...c, goals: c.goals.filter((g) => g.id !== id).map((g) => g.dependsOnGoalId === id ? { ...g, dependsOnGoalId: undefined } : g), tasks: c.tasks.filter((t) => t.goalId !== id), subtasks: c.subtasks.filter((s) => !c.tasks.some((t) => t.goalId === id && t.id === s.taskId)), mindNodes: c.mindNodes.filter((node) => node.goalId !== id) })) }
  async function saveTask(input: Omit<TeamTask, 'id' | 'workspaceId' | 'createdBy' | 'completedAt' | 'sortOrder' | 'points'>, id?: string) { if (!state.activeWorkspaceId || !state.user) return; const data = { project_id: input.projectId || null, goal_id: input.goalId || null, depends_on_task_id: input.dependsOnTaskId || null, title: input.title.trim(), description: input.description.trim(), area: input.area, assignee_id: input.assigneeId || null, status: input.status, priority: input.priority, due_date: input.dueDate || null, waiting_until: input.waitingUntil || null }; if (state.mode === 'cloud' && supabase) return cloud(() => id ? supabase.from('workspace_tasks').update(data).eq('id', id) : supabase.from('workspace_tasks').insert({ ...data, workspace_id: state.activeWorkspaceId, created_by: state.user!.id })); const points = input.priority === 'urgente' ? 30 : input.priority === 'importante' ? 20 : 10; const local = { projectId: input.projectId, goalId: input.goalId, dependsOnTaskId: input.dependsOnTaskId, title: data.title, description: data.description, area: input.area, assigneeId: input.assigneeId, status: input.status, priority: input.priority, dueDate: input.dueDate, waitingUntil: input.waitingUntil, points }; updateDemo((c) => ({ ...c, tasks: id ? c.tasks.map((t) => t.id === id ? { ...t, ...local } : t) : [...c.tasks, { ...local, id: uid(), workspaceId: c.activeWorkspaceId!, createdBy: c.user!.id, sortOrder: c.tasks.filter((t) => t.goalId === input.goalId).length }] })) }
  async function deleteTask(id: string) { if (state.mode === 'cloud' && supabase) return cloud(() => supabase.from('workspace_tasks').delete().eq('id', id)); updateDemo((c) => ({ ...c, tasks: c.tasks.filter((t) => t.id !== id).map((t) => t.dependsOnTaskId === id ? { ...t, dependsOnTaskId: undefined } : t), subtasks: c.subtasks.filter((s) => s.taskId !== id) })) }
  async function moveTask(taskId: string, status: TeamTask['status']) {
    if (state.mode === 'cloud' && supabase) return cloud(() => supabase.from('workspace_tasks').update({ status }).eq('id', taskId))
    updateDemo((c) => {
      const found = c.tasks.find((taskItem) => taskItem.id === taskId); if (!found) return c
      const firstCompletion = status === 'concluida' && !c.activities.some((activity) => activity.id === `task:${taskId}`)
      const taskUserId = found.assigneeId ?? c.user!.id
      const tasks = c.tasks.map((taskItem) => taskItem.id === taskId ? { ...taskItem, status, completedAt: status === 'concluida' ? (taskItem.completedAt ?? new Date().toISOString()) : undefined } : taskItem)
      const goals = c.goals.map((goalItem) => {
        if (goalItem.id !== found.goalId) return goalItem
        const related = tasks.filter((taskItem) => taskItem.goalId === goalItem.id); const current = related.filter((taskItem) => taskItem.status === 'concluida').length; const completed = related.length > 0 && current === related.length
        return { ...goalItem, current, target: Math.max(goalItem.target, related.length), completed, status: completed ? 'concluida' as const : goalItem.status === 'concluida' ? 'andamento' as const : goalItem.status }
      })
      const completedGoal = goals.find((goalItem) => goalItem.id === found.goalId && goalItem.completed && !c.activities.some((activity) => activity.id === `goal:${goalItem.id}`))
      const goalUserId = completedGoal?.ownerId ?? c.user!.id
      const statusLabels: Record<TeamTask['status'], string> = { backlog: 'Caixa de entrada', hoje: 'Hoje', andamento: 'Em andamento', aguardando: 'Aguardando', revisao: 'Em revisão', concluida: 'Concluída' }
      const statusActivity = status !== found.status ? [{ id: uid(), workspaceId: found.workspaceId, userId: c.user!.id, title: `${statusLabels[status]}: ${found.title}`, points: 0, date: localDate(), type: 'status' as const }] : []
      const newActivities = [...statusActivity, ...(firstCompletion ? [{ id: `task:${taskId}`, workspaceId: found.workspaceId, userId: taskUserId, title: found.title, points: found.points, date: localDate(), type: 'task' as const }] : []), ...(completedGoal ? [{ id: `goal:${completedGoal.id}`, workspaceId: completedGoal.workspaceId, userId: goalUserId, title: `Meta: ${completedGoal.title}`, points: completedGoal.rewardXp, date: localDate(), type: 'goal' as const }] : [])]
      const profiles = c.profiles.map((profileItem) => ({ ...profileItem,
        workspaceXp: profileItem.workspaceXp + (firstCompletion && profileItem.id === taskUserId ? found.points : 0) + (completedGoal && profileItem.id === goalUserId ? completedGoal.rewardXp : 0),
        trophies: profileItem.trophies + (firstCompletion && profileItem.id === taskUserId && found.points >= 30 ? 1 : 0) + (completedGoal && profileItem.id === goalUserId ? 1 : 0),
      }))
      return { ...c, tasks, goals, activities: [...newActivities, ...c.activities], profiles }
    })
  }
  async function saveSubtask(input: Pick<TeamSubtask, 'taskId' | 'title'>, id?: string) { const task = state.tasks.find((t) => t.id === input.taskId); if (!task) return; if (state.mode === 'cloud' && supabase) return cloud(() => id ? supabase.from('workspace_subtasks').update({ title: input.title.trim() }).eq('id', id) : supabase.from('workspace_subtasks').insert({ workspace_id: task.workspaceId, task_id: input.taskId, title: input.title.trim() })); updateDemo((c) => ({ ...c, subtasks: id ? c.subtasks.map((s) => s.id === id ? { ...s, title: input.title.trim() } : s) : [...c.subtasks, { id: uid(), workspaceId: task.workspaceId, taskId: input.taskId, title: input.title.trim(), completed: false, sortOrder: c.subtasks.filter((s) => s.taskId === input.taskId).length }] })) }
  async function toggleSubtask(id: string) { const subtask = state.subtasks.find((s) => s.id === id); if (!subtask) return; if (state.mode === 'cloud' && supabase) return cloud(() => supabase.from('workspace_subtasks').update({ completed: !subtask.completed }).eq('id', id)); updateDemo((c) => ({ ...c, subtasks: c.subtasks.map((s) => s.id === id ? { ...s, completed: !s.completed, completedAt: !s.completed ? new Date().toISOString() : undefined } : s) })) }
  async function deleteSubtask(id: string) { if (state.mode === 'cloud' && supabase) return cloud(() => supabase.from('workspace_subtasks').delete().eq('id', id)); updateDemo((c) => ({ ...c, subtasks: c.subtasks.filter((s) => s.id !== id) })) }
  async function saveIdea(input: Pick<TeamIdea, 'title' | 'notes' | 'status' | 'priority'>, id?: string) { if (!state.activeWorkspaceId || !state.user) return; const data = { title: input.title.trim(), notes: input.notes.trim(), status: input.status, priority: input.priority }; if (state.mode === 'cloud' && supabase) return cloud(() => id ? supabase.from('workspace_ideas').update(data).eq('id', id) : supabase.from('workspace_ideas').insert({ ...data, workspace_id: state.activeWorkspaceId, created_by: state.user!.id })); updateDemo((c) => ({ ...c, ideas: id ? c.ideas.map((i) => i.id === id ? { ...i, ...data } : i) : [{ ...data, id: uid(), workspaceId: c.activeWorkspaceId!, createdBy: c.user!.id, createdAt: new Date().toISOString() }, ...c.ideas] })) }
  async function deleteIdea(id: string) { if (state.mode === 'cloud' && supabase) return cloud(() => supabase.from('workspace_ideas').delete().eq('id', id)); updateDemo((c) => ({ ...c, ideas: c.ideas.filter((i) => i.id !== id) })) }
  async function saveMindNode(input: Pick<TeamMindNode, 'goalId' | 'parentId' | 'title' | 'note'>, nodeId?: string) {
    if (!state.activeWorkspaceId || !state.user) return
    const goalNodes = state.mindNodes.filter((node) => node.goalId === input.goalId)
    if (!nodeId && !canAddMindNode(goalNodes, input.parentId)) throw new Error('Limite do mapa atingido.')
    const data = { title: input.title.trim(), note: input.note.trim() }
    if (state.mode === 'cloud' && supabase) return cloud(() => nodeId ? supabase.from('workspace_mind_nodes').update(data).eq('id', nodeId) : supabase.from('workspace_mind_nodes').insert({ ...data, workspace_id: state.activeWorkspaceId, goal_id: input.goalId, parent_id: input.parentId || null, created_by: state.user!.id }))
    updateDemo((current) => ({ ...current, mindNodes: nodeId ? current.mindNodes.map((node) => node.id === nodeId ? { ...node, ...data } : node) : [...current.mindNodes, { ...data, id: uid(), workspaceId: current.activeWorkspaceId!, goalId: input.goalId, parentId: input.parentId, createdBy: current.user!.id, sortOrder: goalNodes.filter((node) => node.parentId === input.parentId).length }] }))
  }
  async function deleteMindNode(nodeId: string) {
    if (state.mode === 'cloud' && supabase) return cloud(() => supabase.from('workspace_mind_nodes').delete().eq('id', nodeId))
    updateDemo((current) => { const removed = descendantIds(current.mindNodes, nodeId); removed.add(nodeId); return { ...current, mindNodes: current.mindNodes.filter((node) => !removed.has(node.id)) } })
  }
  async function updateHabitPlan(planId: string, values: Partial<Pick<HabitPlan, 'baseline' | 'target' | 'mode' | 'shareWithWorkspace'>>) { if (state.mode === 'cloud' && supabase) return cloud(() => supabase.from('habit_plans').update({ baseline: values.baseline, target: values.target, mode: values.mode, share_with_workspace: values.shareWithWorkspace }).eq('id', planId)); updateDemo((c) => ({ ...c, habitPlans: c.habitPlans.map((p) => p.id === planId ? { ...p, ...values } : p) })) }
  async function logHabit(planId: string, amount: number, craving?: number, note?: string) { if (!state.user) return; if (state.mode === 'cloud' && supabase) return cloud(() => supabase.from('habit_logs').upsert({ plan_id: planId, user_id: state.user!.id, date: localDate(), amount: Math.max(0, amount), craving, note }, { onConflict: 'plan_id,date' })); updateDemo((c) => { const existing = c.habitLogs.find((l) => l.planId === planId && l.date === localDate()); return { ...c, habitLogs: existing ? c.habitLogs.map((l) => l.id === existing.id ? { ...l, amount, craving, note } : l) : [...c.habitLogs, { id: uid(), planId, userId: c.user!.id, date: localDate(), amount, craving, note }] } }) }
  async function createHabit(kind: HabitPlan['kind']) { if (!state.user || state.habitPlans.some((p) => p.userId === state.user!.id && p.kind === kind)) return; const input = { user_id: state.user.id, kind, mode: 'reduzir', baseline: 0, target: 0, unit: kind === 'tabaco' ? 'cigarros/dia' : 'sessões/semana', share_with_workspace: false, workspace_id: state.activeWorkspaceId, started_at: localDate() }; if (state.mode === 'cloud' && supabase) return cloud(() => supabase.from('habit_plans').insert(input)); updateDemo((c) => ({ ...c, habitPlans: [...c.habitPlans, mapHabit({ id: uid(), ...input })] })) }

  return { state, session, actions: { signUp, signIn, signOut, switchDemoUser, createWorkspace, joinWorkspace, setWorkspace, saveProject, deleteProject, saveGoal, deleteGoal, saveTask, deleteTask, moveTask, saveSubtask, toggleSubtask, deleteSubtask, saveIdea, deleteIdea, saveMindNode, deleteMindNode, updateHabitPlan, logHabit, createHabit, refresh } }
}
export type TeamActions = ReturnType<typeof useTeamState>['actions']
