import { useState } from 'react'
import { ArrowRight, CheckCircle2, Cloud, Copy, Database, LogIn, LogOut, ShieldCheck, UserPlus, Users } from 'lucide-react'
import type { Session } from '@supabase/supabase-js'
import type { TeamActions } from '../hooks/useTeamState'
import type { TeamState } from '../types/team'

export function AccountPage({ state, session, actions, notify }: { state: TeamState; session: Session | null; actions: TeamActions; notify: (text: string) => void }) {
  const [mode, setMode] = useState<'login' | 'signup'>('login')
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [working, setWorking] = useState(false); const [message, setMessage] = useState('')
  async function submit(event: React.FormEvent) { event.preventDefault(); setWorking(true); const error = mode === 'login' ? await actions.signIn(email, password) : await actions.signUp(email, password, name); setWorking(false); setMessage(error || (mode === 'signup' ? 'Conta criada. Confira seu e-mail se a confirmação estiver ativa.' : 'Conta conectada.')); }
  if (!state.configured) return <DemoAccount state={state} actions={actions} notify={notify} />
  if (session && state.user) return <div className="page inner-page account-page"><section className="page-heading"><div><p className="eyebrow">CONTA CONECTADA</p><h1>Seu perfil</h1><p>Esta identidade separa seu painel pessoal dos workspaces compartilhados.</p></div><span className="cloud-badge"><Cloud size={16} />Nuvem ativa</span></section><div className="account-grid"><section className="surface profile-summary"><span className="member-avatar" style={{ background: state.user.avatarColor }}>{state.user.displayName.slice(0, 1)}</span><small>JOGADOR</small><h2>{state.user.displayName}</h2><p>{session.user.email}</p><div><span><strong>{state.user.workspaceXp}</strong> XP de equipe</span><span><strong>{state.user.trophies}</strong> troféus</span></div><button className="secondary-button" onClick={() => actions.signOut()}><LogOut size={15} />Sair desta conta</button></section><section className="surface account-security"><ShieldCheck size={22} /><h2>O que fica separado</h2><ul><li><CheckCircle2 />Energia, rotina e painel pessoal pertencem somente a você.</li><li><CheckCircle2 />O workspace mostra tarefas, projetos, objetivos e placar da operação.</li><li><CheckCircle2 />Hábitos só aparecem para o sócio quando você ativa “Compartilhado”.</li></ul></section></div></div>
  return <div className="page inner-page auth-page"><section className="auth-story"><span><Users size={28} /></span><p className="eyebrow">DOIS JOGADORES, UMA OPERAÇÃO</p><h1>Cada pessoa com sua conta. O trabalho no mesmo lugar.</h1><p>Entre para criar ou acessar o Metas Business sem abrir seu painel pessoal para outra pessoa.</p><div><span><ShieldCheck />Dados isolados por workspace</span><span><Cloud />Atualização entre aparelhos</span></div></section><section className="auth-card"><div className="auth-tabs"><button className={mode === 'login' ? 'active' : ''} onClick={() => setMode('login')}>Entrar</button><button className={mode === 'signup' ? 'active' : ''} onClick={() => setMode('signup')}>Criar conta</button></div><form onSubmit={submit}>{mode === 'signup' && <label>Como quer aparecer?<input value={name} onChange={(event) => setName(event.target.value)} required minLength={2} /></label>}<label>E-mail<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>Senha<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required minLength={6} /></label>{message && <p className={message.toLowerCase().includes('criada') || message.toLowerCase().includes('conectada') ? 'auth-success' : 'field-error'}>{message}</p>}<button className="primary-button" disabled={working}>{mode === 'login' ? <LogIn size={16} /> : <UserPlus size={16} />}{working ? 'Conectando...' : mode === 'login' ? 'Entrar na minha conta' : 'Criar conta'}<ArrowRight size={15} /></button></form></section></div>
}

function DemoAccount({ state, actions, notify }: { state: TeamState; actions: TeamActions; notify: (text: string) => void }) {
  return <div className="page inner-page account-page"><section className="page-heading"><div><p className="eyebrow">MODO DEMONSTRAÇÃO</p><h1>Experimente a colaboração agora.</h1><p>Para sincronizar dois aparelhos, conecte um projeto Supabase.</p></div><span className="demo-badge">Dados locais</span></section><div className="account-grid"><section className="surface demo-players"><div className="section-title compact"><div><p className="eyebrow">TROCAR JOGADOR</p><h2>Simule os dois sócios</h2></div><Users size={20} /></div>{state.profiles.map((profile) => <button key={profile.id} className={state.user?.id === profile.id ? 'active' : ''} onClick={() => { actions.switchDemoUser(profile.id); notify(`Agora você está simulando ${profile.displayName}.`) }}><span className="player-avatar" style={{ background: profile.avatarColor }}>{profile.displayName.slice(0, 1)}</span><div><strong>{profile.displayName}</strong><small>{profile.workspaceXp} XP · {profile.trophies} troféus</small></div>{state.user?.id === profile.id && <CheckCircle2 size={18} />}</button>)}</section><section className="surface setup-card"><Database size={22} /><h2>Ativar contas reais</h2><ol><li>Crie um projeto gratuito no Supabase.</li><li>Execute a migration da pasta <code>supabase/migrations</code>.</li><li>Cadastre na Vercel `VITE_SUPABASE_URL` e `VITE_SUPABASE_ANON_KEY`.</li><li>Faça um novo deploy.</li></ol><button className="secondary-button" onClick={() => { navigator.clipboard?.writeText('VITE_SUPABASE_URL\\nVITE_SUPABASE_ANON_KEY'); notify('Nomes das variáveis copiados.') }}><Copy size={15} />Copiar nomes das variáveis</button></section></div></div>
}
