import { useState } from 'react'
import { ArrowRight, BookOpen, BrainCircuit, CalendarClock, Check, CheckCircle2, ChevronRight, Circle, Clock3, Flag, FolderKanban, Heart, History, Lightbulb, Medal, Pencil, Play, Plus, Target, TimerReset, Trash2 } from 'lucide-react'
import { MindMap } from '../components/MindMap'
import { clampProgress } from '../lib/stats'
import { localDate } from '../lib/store'
import type { FocoActions } from '../hooks/useFocoState'
import type { AppState, PlanningTab, Technique } from '../types'

const techniques: Technique[] = [
  { id: 'sprint-gentil', name: 'Sprint gentil', rhythm: '15 min foco · 5 min pausa', bestFor: 'Pouca energia ou resistência para começar', description: 'Você promete só quinze minutos. Ao terminar, decide conscientemente se continua.', benefit: 'Reduz o peso do começo e evita o “já que comecei, preciso terminar tudo”.' },
  { id: 'pomodoro', name: 'Pomodoro clássico', rhythm: '25 min foco · 5 min pausa', bestFor: 'Tarefas claras e energia estável', description: 'Trabalhe em uma coisa até o alarme e faça uma pausa curta longe da tela.', benefit: 'Cria urgência saudável e protege contra mergulhos longos demais.' },
  { id: 'timeboxing', name: 'Blocos flexíveis', rhythm: '45 min foco · 15 min pausa', bestFor: 'Trabalho criativo ou estudo profundo', description: 'Reserve um bloco no relógio para uma entrega específica, não para um projeto inteiro.', benefit: 'Dá contorno ao tempo e reduz a sensação de tarefa infinita.' },
  { id: 'primeiro-passo', name: 'Regra do primeiro passo', rhythm: '2 min para destravar', bestFor: 'Paralisia, ansiedade ou tarefa vaga', description: 'Faça apenas a menor ação física possível: abrir o arquivo, separar o material ou escrever o título.', benefit: 'Troca motivação por movimento. Depois de dois minutos, parar continua permitido.' },
]

export function PlanningPage({ state, actions, tab, setTab, openRoutine, openProject, openGoal, openMission, openMilestone, notify }: {
  state: AppState; actions: FocoActions; tab: PlanningTab; setTab: (tab: PlanningTab) => void; openRoutine: () => void; openProject: () => void; openGoal: () => void; openMission: (goalId: string) => void; openMilestone: (projectId: string) => void; notify: (text: string) => void
}) {
  return <div className="page inner-page planning-page">
    <section className="page-heading"><div><p className="eyebrow">CLAREZA ANTES DE PRESSA</p><h1>Planejamento</h1><p>Um lugar para decidir com calma antes do dia decidir por você.</p></div></section>
    <div className="planning-tabs" role="tablist"><button className={tab === 'rotina' ? 'active' : ''} onClick={() => setTab('rotina')}><CalendarClock size={18} /><span>Rotina</span><small>desenhar o dia</small></button><button className={tab === 'projetos' ? 'active' : ''} onClick={() => setTab('projetos')}><FolderKanban size={18} /><span>Projetos</span><small>tirar do papel</small></button><button className={tab === 'objetivos' ? 'active' : ''} onClick={() => setTab('objetivos')}><Target size={18} /><span>Objetivos</span><small>escolher direção</small></button></div>
    {tab === 'rotina' && <RoutinePlanner state={state} actions={actions} openRoutine={openRoutine} />}
    {tab === 'projetos' && <ProjectsPlanner state={state} actions={actions} openProject={openProject} openMilestone={openMilestone} />}
    {tab === 'objetivos' && <GoalsPlanner state={state} actions={actions} openGoal={openGoal} openMission={openMission} notify={notify} />}
  </div>
}

function RoutinePlanner({ state, actions, openRoutine }: { state: AppState; actions: FocoActions; openRoutine: () => void }) {
  const selected = techniques.find((item) => item.id === state.routine.technique)!
  const today = localDate()
  return <div className="planner-content">
    <section className="planner-hero routine-hero"><div><p className="card-label"><Heart size={15} /> INTENÇÃO DA ROTINA</p><h2>Uma rotina é um apoio, não uma prova.</h2><textarea aria-label="Intenção da rotina" value={state.routine.intention} onChange={(event) => actions.updateRoutine({ intention: event.target.value })} rows={2} /></div><div className="day-boundaries"><label>Quero começar por volta de<input type="time" value={state.routine.wakeTime} onChange={(event) => actions.updateRoutine({ wakeTime: event.target.value })} /></label><span><ArrowRight size={17} /></span><label>Quero desacelerar por volta de<input type="time" value={state.routine.sleepTime} onChange={(event) => actions.updateRoutine({ sleepTime: event.target.value })} /></label></div></section>
    <section className="planning-section"><div className="section-title"><div><p className="eyebrow">ESCOLHA PARA HOJE</p><h2>Técnica de foco</h2><p>Não existe técnica perfeita. Escolha pela energia e pelo tipo de tarefa.</p></div></div><div className="technique-grid">{techniques.map((item) => <button key={item.id} className={state.routine.technique === item.id ? 'selected' : ''} onClick={() => actions.setTechnique(item.id)}><div><TimerReset size={19} /><span>{item.bestFor}</span></div><h3>{item.name}</h3><strong>{item.rhythm}</strong><p>{item.description}</p>{state.routine.technique === item.id && <i><Check size={14} />Escolhida para hoje</i>}</button>)}</div></section>
    <section className="foundation-note"><Lightbulb size={20} /><div><strong>Por que “{selected.name}” pode ajudar?</strong><p>{selected.benefit}</p></div></section>
    <section className="planning-section"><div className="section-title"><div><p className="eyebrow">ÂNCORAS DO DIA</p><h2>Blocos da rotina</h2><p>Use horários como referência. Atrasar não invalida o bloco.</p></div><button className="quiet-button" onClick={openRoutine}><Plus size={16} />Novo bloco</button></div><div className="schedule-list">{state.routine.blocks.map((block) => { const done = block.completedDates.includes(today); return <article className={done ? 'done' : ''} key={block.id}><div className="schedule-time"><strong>{block.start}</strong><span>{block.end}</span></div><div className="schedule-line"><i /></div><div className="schedule-copy"><span>energia {block.energy}</span><h3>{block.title}</h3><small>{daysText(block.days)}</small></div><button onClick={() => actions.toggleRoutineBlock(block.id)}>{done ? <CheckCircle2 size={20} /> : <Circle size={20} />}{done ? 'Feito hoje' : 'Marcar hoje'}</button></article>})}</div></section>
    <section className="study-guide"><div><BookOpen size={20} /><h3>Fundamentos que funcionam melhor que força de vontade</h3></div><div className="guide-grid"><article><span>1</span><strong>Externalize o tempo</strong><p>Use alarme e blocos visíveis. Sentir o tempo é mais difícil do que enxergá-lo.</p></article><article><span>2</span><strong>Reduza a partida</strong><p>Planeje o primeiro gesto físico, não “fazer o projeto”.</p></article><article><span>3</span><strong>Proteja transições</strong><p>Deixe cinco minutos entre blocos para água, banheiro e reorganização.</p></article><article><span>4</span><strong>Planeje recuperação</strong><p>Um dia ruim não exige compensação. Retome pelo menor bloco amanhã.</p></article></div></section>
  </div>
}

function ProjectsPlanner({ state, actions, openProject, openMilestone }: { state: AppState; actions: FocoActions; openProject: () => void; openMilestone: (id: string) => void }) {
  return <div className="planner-content"><section className="planner-intro"><div><p className="card-label"><FolderKanban size={15} /> PROJETOS ATIVOS</p><h2>Um projeto só avança quando o próximo marco está claro.</h2><p>Marcos são entregas observáveis. “Pesquisar três opções” funciona melhor do que “avançar no projeto”.</p></div><button className="primary-button" onClick={openProject}><Plus size={17} />Novo projeto</button></section><div className="project-planner-grid">{state.projects.map((project) => <article key={project.id} style={{ '--project': project.color } as React.CSSProperties}><div className="project-plan-head"><span><FolderKanban size={18} /></span><div><small>{project.status} · {project.deadline ? `até ${formatDate(project.deadline)}` : 'sem prazo'}</small><h2>{project.name}</h2></div><strong>{project.progress}%</strong></div><p>{project.why}</p><div className="soft-progress"><i style={{ width: `${project.progress}%` }} /></div><div className="milestone-list">{project.milestones.length ? project.milestones.map((milestone) => <button className={milestone.completed ? 'done' : ''} key={milestone.id} onClick={() => actions.toggleMilestone(project.id, milestone.id)}>{milestone.completed ? <CheckCircle2 size={17} /> : <Circle size={17} />}<span>{milestone.title}</span></button>) : <div className="empty-compact"><p>Sem marcos ainda. Crie a primeira entrega concreta.</p></div>}</div><button className="add-line-button" onClick={() => openMilestone(project.id)}><Plus size={15} />Adicionar marco</button></article>)}</div><section className="foundation-note"><Flag size={20} /><div><strong>Um bom marco termina em algo que você consegue apontar.</strong><p>Documento enviado, tela publicada, orçamento escolhido, conversa marcada. Se não dá para saber quando terminou, ainda está grande demais.</p></div></section></div>
}

function GoalsPlanner({ state, actions, openGoal, openMission, notify }: { state: AppState; actions: FocoActions; openGoal: () => void; openMission: (goalId: string) => void; notify: (text: string) => void }) {
  const [selectedId, setSelected] = useState(state.goals[0]?.id ?? ''); const [view, setView] = useState<'execucao' | 'mapa' | 'historico'>('execucao'); const [editing, setEditing] = useState(false)
  const selected = state.goals.find((goal) => goal.id === selectedId) ?? state.goals[0]; const missions = selected ? state.missions.filter((mission) => mission.goalId === selected.id) : []; const completed = missions.filter((mission) => mission.completed); const progress = missions.length ? Math.round(completed.length / missions.length * 100) : selected ? clampProgress(selected.current, selected.target) : 0
  const history = selected ? state.activities.filter((activity) => activity.title === `Objetivo alcançado: ${selected.title}` || activity.title === `Avancei em ${selected.title}` || missions.some((mission) => mission.title === activity.title || activity.title.endsWith(`: ${mission.title}`))) : []
  return <div className="planner-content"><section className="planner-intro goal-intro"><div><p className="card-label"><Target size={15} /> DIREÇÃO PESSOAL</p><h2>Metas com progresso visível.</h2><p>Escolha uma meta, veja o próximo passo e marque o que terminou.</p></div><button className="primary-button" onClick={openGoal}><Plus size={17} />Nova meta</button></section>{state.goals.length ? <div className="personal-goals-layout"><aside className="personal-goal-list">{state.goals.map((goal) => { const linked = state.missions.filter((mission) => mission.goalId === goal.id); const done = linked.filter((mission) => mission.completed).length; const value = linked.length ? Math.round(done / linked.length * 100) : clampProgress(goal.current, goal.target); return <button key={goal.id} className={selected?.id === goal.id ? 'selected' : ''} onClick={() => { setSelected(goal.id); setView('execucao'); setEditing(false) }}><span>{areaIcon(goal.area)}</span><div><small>{goal.area} · {formatDate(goal.deadline)}</small><strong>{goal.title}</strong><div className="soft-progress"><i style={{ width: `${value}%` }} /></div><em>{done}/{linked.length} tarefas · {value}%</em></div><ChevronRight size={16} /></button> })}</aside>{selected && <section className="personal-goal-detail"><header><div><span className="goal-area-label">{selected.area}</span><h2>{selected.title}</h2><p>{selected.why}</p></div><div><button className="icon-button" onClick={() => setEditing(!editing)} aria-label="Editar meta"><Pencil size={16} /></button><button className="icon-button danger" onClick={() => { if (window.confirm('Excluir esta meta? As tarefas serão mantidas sem vínculo.')) { actions.deleteGoal(selected.id); setSelected(''); notify('Meta excluída.') } }} aria-label="Excluir meta"><Trash2 size={16} /></button></div></header>{editing && <PersonalGoalEditor goal={selected} save={(values) => { actions.updateGoal(selected.id, values); setEditing(false); notify('Meta atualizada.') }} />}
    <div className="personal-goal-score"><div className="goal-progress-ring" style={{ '--goal-progress': `${progress * 3.6}deg` } as React.CSSProperties}><strong>{progress}%</strong><span>concluído</span></div><div><span><small>Tarefas feitas</small><strong>{completed.length}/{missions.length}</strong></span><span><small>XP conquistado</small><strong>{completed.reduce((sum, mission) => sum + mission.xp, 0)} XP</strong></span><span><small>Moedas disponíveis</small><strong>{missions.filter((mission) => !mission.completed).reduce((sum, mission) => sum + mission.coins, 0) + (selected.completed ? 0 : selected.rewardCoins)}</strong></span></div></div>
    <div className="goal-view-tabs"><button className={view === 'execucao' ? 'active' : ''} onClick={() => setView('execucao')}><CheckCircle2 size={16} />Execução</button><button className={view === 'mapa' ? 'active' : ''} onClick={() => setView('mapa')}><BrainCircuit size={16} />Mapa mental</button><button className={view === 'historico' ? 'active' : ''} onClick={() => setView('historico')}><History size={16} />Histórico</button></div>
    {view === 'execucao' && <div className="personal-task-area"><div className="section-title compact"><div><p className="eyebrow">PRÓXIMOS PASSOS</p><h3>Tarefas da meta</h3></div><button className="quiet-button" onClick={() => openMission(selected.id)}><Plus size={15} />Nova tarefa</button></div>{missions.length ? missions.map((mission, index) => <article className={`personal-goal-task ${mission.completed ? 'done' : ''}`} key={mission.id}><span>{mission.completed ? <CheckCircle2 /> : index + 1}</span><div><h4>{mission.title}</h4><p>{mission.description}</p><small>{mission.duration} min · +{mission.xp} XP · +{mission.coins} moedas</small>{mission.status === 'aguardando' && mission.waitingUntil && <i><Clock3 size={13} />Aguardando até {new Date(mission.waitingUntil).toLocaleString('pt-BR')}</i>}</div><div>{mission.completed ? <button className="secondary-button" onClick={() => actions.setMissionStatus(mission.id, 'andamento')}><Play size={14} />Reabrir</button> : <><button className="complete-task-button" onClick={() => { actions.completeMission(mission.id); notify(`Tarefa concluída: +${mission.xp} XP e +${mission.coins} moedas.`) }}><CheckCircle2 size={15} />Marcar concluída</button><button className="secondary-button" onClick={() => { actions.setMissionStatus(mission.id, 'aguardando', new Date(Date.now() + 86_400_000).toISOString()); notify('Tarefa aguardando por 24 horas.') }}><Clock3 size={14} />Aguardar 24h</button></>}</div></article>) : <div className="empty-state"><CheckCircle2 size={22} /><h3>Nenhuma tarefa vinculada</h3><p>Crie o primeiro passo para esta meta começar a andar.</p><button onClick={() => openMission(selected.id)}>Adicionar tarefa</button></div>}<section className="personal-final-bonus"><Medal size={19} /><div><strong>Bônus da meta: {selected.rewardCoins} moedas</strong><p>{missions.length > 0 && completed.length === missions.length ? 'Todas as tarefas foram feitas. Resgate a conclusão da meta.' : 'Registre avanços que aconteceram fora das tarefas.'}</p></div><button disabled={selected.completed} onClick={() => actions.advanceGoal(selected.id, missions.length > 0 && completed.length === missions.length ? selected.target - selected.current : 1)}>{selected.completed ? 'Meta concluída' : missions.length > 0 && completed.length === missions.length ? 'Concluir meta' : 'Registrar avanço'}</button></section></div>}
    {view === 'mapa' && <MindMap goalTitle={selected.title} nodes={state.mindNodes.filter((node) => node.goalId === selected.id)} save={(input, id) => actions.saveMindNode({ ...input, goalId: selected.id }, id)} remove={actions.deleteMindNode} notify={notify} />}
    {view === 'historico' && <div className="goal-history">{history.length ? [...history].reverse().map((activity) => <article key={activity.id}><span className="history-mark"><History size={14} /></span><div><strong>{activity.title}</strong><small>{formatDate(activity.date)}</small></div><b>{activity.xp ? `+${activity.xp} XP` : `${activity.coins} moedas`}</b></article>) : <div className="empty-state"><History size={22} /><h3>Histórico vazio</h3><p>Conclusões e avanços desta meta aparecerão aqui.</p></div>}</div>}</section>}</div> : <div className="empty-state"><Target size={26} /><h3>Nenhuma meta pessoal</h3><p>Crie uma meta para organizar tarefas, mapa mental e progresso.</p><button onClick={openGoal}>Criar primeira meta</button></div>}</div>
}

function PersonalGoalEditor({ goal, save }: { goal: AppState['goals'][number]; save: (values: Partial<AppState['goals'][number]>) => void }) { const [title, setTitle] = useState(goal.title); const [why, setWhy] = useState(goal.why); const [deadline, setDeadline] = useState(goal.deadline); return <div className="personal-goal-editor"><label>Nome<input value={title} onChange={(event) => setTitle(event.target.value)} /></label><label>Por que importa<textarea rows={2} value={why} onChange={(event) => setWhy(event.target.value)} /></label><label>Prazo<input type="date" value={deadline} onChange={(event) => setDeadline(event.target.value)} /></label><button className="primary-button" disabled={title.trim().length < 3} onClick={() => save({ title: title.trim(), why: why.trim(), deadline })}>Salvar alterações</button></div> }

function daysText(days: number[]) { if (days.length === 7) return 'todos os dias'; if (days.join(',') === '1,2,3,4,5') return 'segunda a sexta'; return `${days.length} dias por semana` }
function formatDate(date: string) { return new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short' }).format(new Date(`${date}T12:00:00`)) }
function areaIcon(area: AppState['goals'][number]['area']) { return area === 'saude' ? 'S' : area === 'carreira' ? 'C' : area === 'relacoes' ? 'R' : 'P' }
