import { useEffect, useState } from 'react'
import { Activity, ArrowRight, BrainCircuit, BriefcaseBusiness, CalendarDays, CheckCircle2, ChevronRight, ClipboardList, Clock3, Coins, Copy, Crown, FolderKanban, Goal, History, Lightbulb, ListChecks, LockKeyhole, Medal, Pencil, Play, Plus, ShieldCheck, Trash2, Trophy, UserRoundPlus, Users, X } from 'lucide-react'
import { MindMap } from '../components/MindMap'
import { pointsForPriority, workspaceRanking } from '../lib/teamStats'
import type { TeamActions } from '../hooks/useTeamState'
import type { GoalStatus, IdeaStatus, TeamArea, TeamGoal, TeamIdea, TeamPriority, TeamProject, TeamState, TeamTask, TeamTaskStatus } from '../types/team'

type TeamTab = 'metas' | 'quadro' | 'operacoes' | 'ideias' | 'ranking' | 'equipe'
type Dialog = { kind: 'goal'; item?: TeamGoal; projectId?: string } | { kind: 'task'; item?: TeamTask; goalId?: string } | { kind: 'project'; item?: TeamProject } | { kind: 'idea'; item?: TeamIdea } | null
const statuses: { id: TeamTaskStatus; label: string }[] = [{ id: 'backlog', label: 'Caixa de entrada' }, { id: 'hoje', label: 'Hoje' }, { id: 'andamento', label: 'Em andamento' }, { id: 'aguardando', label: 'Aguardando' }, { id: 'revisao', label: 'Revisão' }, { id: 'concluida', label: 'Concluídas' }]
const areaLabels: Record<TeamArea, string> = { trafego: 'Tráfego', sites: 'Sites', campanhas: 'Campanhas', clientes: 'Clientes', vsl: 'VSL', operacao: 'Operação', estudo: 'Estudo', geral: 'Geral' }
const priorityLabels: Record<TeamPriority, string> = { urgente: 'Foco principal', importante: 'Alta', normal: 'Normal' }
const goalStatusLabels: Record<GoalStatus, string> = { planejada: 'Planejada', andamento: 'Em andamento', bloqueada: 'Bloqueada', concluida: 'Concluída' }

export function TeamPage({ state, actions, openAccount, notify }: { state: TeamState; actions: TeamActions; openAccount: () => void; notify: (text: string) => void }) {
  const [tab, setTab] = useState<TeamTab>('metas'); const [dialog, setDialog] = useState<Dialog>(null); const [selectedGoalId, setSelectedGoalId] = useState<string | null>(state.goals[0]?.id ?? null)
  const active = state.workspaces.find((item) => item.id === state.activeWorkspaceId)
  if (state.configured && !state.user) return <TeamGate openAccount={openAccount} />
  if (state.loading) return <div className="page inner-page"><div className="team-loading"><Activity className="spin" /><h2>Sincronizando a operação...</h2><p>Buscando metas, tarefas e jogadores.</p></div></div>
  if (!active) return <EmptyWorkspace actions={actions} />
  const memberProfiles = state.profiles.filter((profile) => state.members.some((member) => member.workspaceId === active.id && member.userId === profile.id))
  const selectedGoal = state.goals.find((goal) => goal.id === selectedGoalId) ?? null
  return <div className="page inner-page team-page">
    <section className="team-hero"><div><p className="eyebrow">ESPAÇO COMPARTILHADO</p><div className="workspace-title"><span><BriefcaseBusiness size={22} /></span><div><h1>{active.name}</h1><p>{active.description}</p></div></div></div><div className="workspace-actions"><span className={`sync-state ${state.mode}`}><i />{state.mode === 'cloud' ? 'Sincronizado' : 'Demonstração local'}</span><button className="secondary-button" onClick={() => copyInvite(active.inviteCode, notify)}><Copy size={15} />Convidar sócio</button><button className="primary-button" onClick={() => setDialog({ kind: 'goal' })}><Plus size={16} />Nova meta</button></div></section>
    {state.error && <div className="inline-error">{state.error}</div>}
    <div className="team-tabs" role="tablist">{([['metas', Goal, 'Metas'], ['quadro', ClipboardList, 'Quadro'], ['operacoes', FolderKanban, 'Operações'], ['ideias', Lightbulb, 'Ideias'], ['ranking', Trophy, 'Ranking'], ['equipe', Users, 'Equipe']] as const).map(([id, Icon, label]) => <button key={id} role="tab" aria-selected={tab === id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}><Icon size={16} />{label}</button>)}</div>
    {tab === 'metas' && <GoalsHub state={state} selected={selectedGoal} select={setSelectedGoalId} edit={(item) => setDialog({ kind: 'goal', item })} add={() => setDialog({ kind: 'goal' })} addTask={(goalId) => setDialog({ kind: 'task', goalId })} editTask={(item) => setDialog({ kind: 'task', item })} actions={actions} notify={notify} />}
    {tab === 'quadro' && <TeamBoard state={state} actions={actions} edit={(item) => setDialog({ kind: 'task', item })} />}
    {tab === 'operacoes' && <Operations state={state} edit={(item) => setDialog({ kind: 'project', item })} add={() => setDialog({ kind: 'project' })} open={(projectId) => { const goal = state.goals.find((item) => item.projectId === projectId); if (goal) { setSelectedGoalId(goal.id); setTab('metas') } else setDialog({ kind: 'goal', projectId }) }} />}
    {tab === 'ideias' && <Ideas state={state} edit={(item) => setDialog({ kind: 'idea', item })} add={() => setDialog({ kind: 'idea' })} />}
    {tab === 'ranking' && <TeamRanking state={state} profiles={memberProfiles} />}
    {tab === 'equipe' && <TeamMembers state={state} profiles={memberProfiles} inviteCode={active.inviteCode} notify={notify} />}
    {dialog?.kind === 'goal' && <GoalDialog state={state} actions={actions} item={dialog.item} initialProjectId={dialog.projectId} close={() => setDialog(null)} notify={notify} />}
    {dialog?.kind === 'task' && <TaskDialog state={state} actions={actions} item={dialog.item} initialGoalId={dialog.goalId} close={() => setDialog(null)} notify={notify} />}
    {dialog?.kind === 'project' && <ProjectDialog actions={actions} item={dialog.item} close={() => setDialog(null)} notify={notify} />}
    {dialog?.kind === 'idea' && <IdeaDialog actions={actions} item={dialog.item} close={() => setDialog(null)} notify={notify} />}
  </div>
}

function GoalsHub({ state, selected, select, edit, add, addTask, editTask, actions, notify }: { state: TeamState; selected: TeamGoal | null; select: (id: string) => void; edit: (item: TeamGoal) => void; add: () => void; addTask: (id: string) => void; editTask: (item: TeamTask) => void; actions: TeamActions; notify: (text: string) => void }) {
  const goals = [...state.goals].sort((a, b) => ({ urgente: 0, importante: 1, normal: 2 }[a.priority] - { urgente: 0, importante: 1, normal: 2 }[b.priority] || a.sortOrder - b.sortOrder))
  return <div className="goals-layout"><section className="goal-master"><div className="section-title"><div><p className="eyebrow">DIREÇÃO DA DUPLA</p><h2>Metas por prioridade</h2></div><button className="quiet-button" onClick={add}><Plus size={15} />Adicionar</button></div>{goals.length ? goals.map((goal) => { const related = state.tasks.filter((task) => task.goalId === goal.id); const done = related.filter((task) => task.status === 'concluida').length; const progress = related.length ? Math.round(done / related.length * 100) : 0; const project = state.projects.find((item) => item.id === goal.projectId); return <button key={goal.id} className={`goal-master-card priority-${goal.priority} ${selected?.id === goal.id ? 'selected' : ''}`} onClick={() => select(goal.id)}><div><span className="priority-pill">{priorityLabels[goal.priority]}</span><small>{goalStatusLabels[goal.status]}</small></div><h3>{goal.title}</h3><p>{project?.name ?? 'Sem operação vinculada'}</p><div className="soft-progress"><i style={{ width: `${progress}%` }} /></div><footer><span>{done}/{related.length} etapas</span><strong>{progress}%</strong></footer></button> }) : <Empty title="Nenhuma meta ainda" text="Crie a primeira meta e deixe o próximo passo visível." action="Criar meta" onAction={add} />}</section>
    <section className="goal-detail">{selected ? <GoalDetail goal={selected} state={state} edit={() => edit(selected)} addTask={() => addTask(selected.id)} editTask={editTask} actions={actions} notify={notify} /> : <Empty title="Escolha uma meta" text="Os detalhes, tarefas e dependências aparecem aqui." />}</section></div>
}

function GoalDetail({ goal, state, edit, addTask, editTask, actions, notify }: { goal: TeamGoal; state: TeamState; edit: () => void; addTask: () => void; editTask: (item: TeamTask) => void; actions: TeamActions; notify: (text: string) => void }) {
  const [view, setView] = useState<'execucao' | 'mapa' | 'historico'>('execucao')
  const tasks = [...state.tasks.filter((item) => item.goalId === goal.id)].sort((a, b) => a.sortOrder - b.sortOrder); const project = state.projects.find((item) => item.id === goal.projectId); const dependency = state.goals.find((item) => item.id === goal.dependsOnGoalId); const owner = state.profiles.find((item) => item.id === goal.ownerId)
  const done = tasks.filter((task) => task.status === 'concluida'); const progress = tasks.length ? Math.round(done.length / tasks.length * 100) : 0; const earned = done.reduce((sum, task) => sum + task.points, 0) + (goal.completed ? goal.rewardXp : 0); const available = tasks.filter((task) => task.status !== 'concluida').reduce((sum, task) => sum + task.points, 0) + (goal.completed ? 0 : goal.rewardXp)
  const taskTitles = new Set(tasks.map((task) => task.title)); const history = state.activities.filter((activity) => activity.title === `Meta: ${goal.title}` || taskTitles.has(activity.title) || [...taskTitles].some((title) => activity.title.endsWith(`: ${title}`)))
  return <><header className="goal-detail-head"><div><div className="goal-kickers"><span className={`priority-pill priority-${goal.priority}`}>{priorityLabels[goal.priority]}</span><span>{goalStatusLabels[goal.status]}</span></div><h2>{goal.title}</h2><p>{goal.description || 'Sem descrição.'}</p></div><button className="icon-button" onClick={edit} aria-label="Editar meta"><Pencil size={17} /></button></header>
    <div className="goal-progress-overview"><div className="goal-progress-ring" style={{ '--goal-progress': `${progress * 3.6}deg` } as React.CSSProperties}><strong>{progress}%</strong><span>concluído</span></div><div><span><small>Etapas feitas</small><strong>{done.length} de {tasks.length}</strong></span><span><small>XP conquistado</small><strong>{earned} XP</strong></span><span><small>XP disponível</small><strong>{available} XP</strong></span></div></div>
    <div className="goal-meta"><span><FolderKanban size={15} /><small>Operação</small><strong>{project?.name ?? 'Não vinculada'}</strong></span><span><CalendarDays size={15} /><small>Prazo</small><strong>{goal.deadline ? formatDate(goal.deadline) : 'Sem prazo'}</strong></span><span><LockKeyhole size={15} /><small>Depende de</small><strong>{dependency?.title ?? 'Nada'}</strong></span><span><Users size={15} /><small>Responsável</small><strong>{owner?.displayName ?? 'A dupla'}</strong></span></div>
    <div className="goal-view-tabs"><button className={view === 'execucao' ? 'active' : ''} onClick={() => setView('execucao')}><ListChecks size={16} />Execução</button><button className={view === 'mapa' ? 'active' : ''} onClick={() => setView('mapa')}><BrainCircuit size={16} />Mapa mental</button><button className={view === 'historico' ? 'active' : ''} onClick={() => setView('historico')}><History size={16} />Histórico</button></div>
    {view === 'execucao' && <><section className="bonus-panel"><Medal size={21} /><div><strong>Bônus final: +{goal.rewardXp} XP e 1 troféu</strong><p>Liberado uma única vez quando todas as tarefas forem concluídas.</p></div></section><div className="section-title compact"><div><p className="eyebrow">PLANO DE EXECUÇÃO</p><h3>Tarefas em ordem</h3></div><button className="quiet-button" onClick={addTask}><Plus size={15} />Nova tarefa</button></div><div className="goal-task-list">{tasks.map((task, index) => <GoalTask key={task.id} index={index} task={task} state={state} actions={actions} edit={() => editTask(task)} notify={notify} />)}{!tasks.length && <Empty title="Sem tarefas" text="Divida esta meta em próximos passos pequenos e verificáveis." action="Adicionar tarefa" onAction={addTask} />}</div></>}
    {view === 'mapa' && <MindMap goalTitle={goal.title} nodes={state.mindNodes.filter((node) => node.goalId === goal.id)} save={(input, id) => actions.saveMindNode({ ...input, goalId: goal.id }, id)} remove={actions.deleteMindNode} notify={notify} />}
    {view === 'historico' && <div className="goal-history">{history.length ? history.map((activity) => <article key={activity.id}><span className={`history-mark ${activity.type}`}><History size={14} /></span><div><strong>{activity.title}</strong><small>{formatDate(activity.date)} · {state.profiles.find((profile) => profile.id === activity.userId)?.displayName ?? 'Jogador'}</small></div><b>{activity.points ? `+${activity.points} XP` : 'Atualização'}</b></article>) : <Empty title="Nenhum movimento ainda" text="Alterações de status e conclusões aparecerão aqui." />}</div>}
  </>
}

function GoalTask({ index, task, state, actions, edit, notify }: { index: number; task: TeamTask; state: TeamState; actions: TeamActions; edit: () => void; notify: (text: string) => void }) {
  const [subtask, setSubtask] = useState(''); const [now, setNow] = useState(Date.now()); const depends = state.tasks.find((item) => item.id === task.dependsOnTaskId); const items = state.subtasks.filter((item) => item.taskId === task.id).sort((a, b) => a.sortOrder - b.sortOrder); const blocked = depends && depends.status !== 'concluida'; const waitingMs = task.waitingUntil ? new Date(task.waitingUntil).getTime() - now : 0
  useEffect(() => { if (task.status !== 'aguardando' || !task.waitingUntil) return; const timer = window.setInterval(() => setNow(Date.now()), 60_000); return () => window.clearInterval(timer) }, [task.status, task.waitingUntil])
  return <article className={`goal-task ${task.status === 'concluida' ? 'done' : ''} ${task.status === 'aguardando' ? 'waiting' : ''}`}><div className="task-order">{task.status === 'concluida' ? <CheckCircle2 /> : index + 1}</div><div className="goal-task-body"><div><h4>{task.title}</h4><button className="icon-button mini" onClick={edit} aria-label={`Editar ${task.title}`}><Pencil size={14} /></button></div>{task.description && <p>{task.description}</p>}<div className="task-flags"><span>{areaLabels[task.area]}</span><span className="xp-chip">+{task.points} XP</span><span>{statuses.find((status) => status.id === task.status)?.label}</span>{blocked && <span className="blocked"><LockKeyhole size={12} />Aguarda: {depends.title}</span>}</div>{task.status === 'aguardando' && task.waitingUntil && <div className={`waiting-card ${waitingMs <= 0 ? 'ready' : ''}`}><Clock3 size={17} /><div><strong>{waitingMs > 0 ? 'Tempo de espera em andamento' : 'Tempo de espera finalizado'}</strong><small>{waitingMs > 0 ? `${formatRemaining(waitingMs)} restantes · termina ${formatDateTime(task.waitingUntil)}` : 'Agora você já pode marcar esta tarefa como concluída.'}</small></div></div>}{items.length > 0 && <div className="subtask-list">{items.map((item) => <div key={item.id}><button onClick={() => actions.toggleSubtask(item.id)}>{item.completed ? <CheckCircle2 size={16} /> : <span className="empty-check" />}{item.title}</button><button aria-label={`Excluir ${item.title}`} onClick={() => confirmDelete('esta subtarefa', () => actions.deleteSubtask(item.id), notify)}><X size={13} /></button></div>)}</div>}<div className="task-primary-actions"><button className={task.status === 'concluida' ? 'secondary-button' : 'complete-task-button'} disabled={Boolean(blocked)} onClick={() => actions.moveTask(task.id, task.status === 'concluida' ? 'andamento' : 'concluida')}>{task.status === 'concluida' ? <><Play size={15} />Reabrir tarefa</> : <><CheckCircle2 size={16} />Marcar como concluída · +{task.points} XP</>}</button>{task.status !== 'concluida' && <button className="secondary-button" onClick={edit}><Clock3 size={15} />{task.status === 'aguardando' ? 'Editar espera' : 'Colocar em espera'}</button>}</div><form className="quick-subtask" onSubmit={async (event) => { event.preventDefault(); if (!subtask.trim()) return; try { await actions.saveSubtask({ taskId: task.id, title: subtask }); setSubtask(''); notify('Subtarefa adicionada.') } catch { notify('Não foi possível adicionar a subtarefa.') } }}><input value={subtask} onChange={(event) => setSubtask(event.target.value)} placeholder="Adicionar subtarefa" aria-label={`Nova subtarefa de ${task.title}`} /><button disabled={!subtask.trim()}><Plus size={14} /></button></form></div></article>
}

function TeamBoard({ state, actions, edit }: { state: TeamState; actions: TeamActions; edit: (item: TeamTask) => void }) { return <div className="kanban-board">{statuses.map((column) => { const items = state.tasks.filter((item) => item.status === column.id); return <section className="kanban-column" key={column.id}><header><span>{column.label}</span><i>{items.length}</i></header><div>{items.map((task) => <article className={`team-task priority-${task.priority}`} key={task.id}><div><span className="area-chip">{areaLabels[task.area]}</span><button className="icon-button mini" onClick={() => edit(task)}><Pencil size={14} /></button></div><h3>{task.title}</h3><p>{task.description}</p><footer><PlayerAvatar state={state} id={task.assigneeId} /><select aria-label={`Mover ${task.title}`} value={task.status} onChange={(event) => actions.moveTask(task.id, event.target.value as TeamTaskStatus)}>{statuses.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></footer></article>)}</div></section> })}</div> }

function Operations({ state, edit, add, open }: { state: TeamState; edit: (item: TeamProject) => void; add: () => void; open: (id: string) => void }) { return <div className="team-content"><section className="section-title"><div><p className="eyebrow">ÁREAS DE TRABALHO</p><h2>Operações</h2></div><button className="primary-button" onClick={add}><Plus size={15} />Nova operação</button></section><div className="team-project-grid">{[...state.projects].sort((a, b) => a.sortOrder - b.sortOrder).map((project) => { const goals = state.goals.filter((item) => item.projectId === project.id); const tasks = state.tasks.filter((item) => item.projectId === project.id); const done = tasks.filter((item) => item.status === 'concluida').length; const progress = tasks.length ? Math.round(done / tasks.length * 100) : 0; return <article key={project.id} style={{ '--project': project.color } as React.CSSProperties}><button className="icon-button project-edit" onClick={() => edit(project)} aria-label={`Editar ${project.name}`}><Pencil size={15} /></button><button className="operation-open" onClick={() => open(project.id)} aria-label={`Abrir operação ${project.name}`}><span><FolderKanban /></span><small>{priorityLabels[project.priority]} · {project.status}</small><h2>{project.name}</h2><p>{project.summary}</p><div className="soft-progress"><i style={{ width: `${progress}%` }} /></div><footer><span>{goals.length} metas · {done}/{tasks.length} tarefas</span><strong>{progress}%</strong></footer><span className="operation-card-cta">{goals.length ? 'Abrir metas' : 'Criar primeira meta'} <ArrowRight size={14} /></span></button></article> })}</div></div> }
function Ideas({ state, edit, add }: { state: TeamState; edit: (item: TeamIdea) => void; add: () => void }) { return <div className="team-content"><section className="section-title"><div><p className="eyebrow">CAPTURE AGORA, DECIDA DEPOIS</p><h2>Caixa de ideias</h2><p>Ideias não viram prioridade automaticamente.</p></div><button className="primary-button" onClick={add}><Plus size={15} />Nova ideia</button></section>{state.ideas.length ? <div className="ideas-grid">{state.ideas.map((idea) => <button key={idea.id} onClick={() => edit(idea)}><div><span className={`priority-pill priority-${idea.priority}`}>{priorityLabels[idea.priority]}</span><small>{idea.status}</small></div><h3>{idea.title}</h3><p>{idea.notes || 'Sem observações.'}</p><span>Editar <ChevronRight size={14} /></span></button>)}</div> : <Empty title="A caixa está vazia" text="Quando surgir algo, registre sem interromper a meta principal." action="Registrar ideia" onAction={add} />}</div> }

function TeamRanking({ state, profiles }: { state: TeamState; profiles: TeamState['profiles'] }) { const [period, setPeriod] = useState<'dia' | 'semana'>('semana'); const ranking = workspaceRanking(profiles, state.activities, period === 'dia' ? 1 : 7); return <div className="team-content"><section className="ranking-hero"><div><p className="eyebrow">COMPETIÇÃO LEVE</p><h2>Ranking da dupla</h2><p>O placar celebra entregas; não mede valor pessoal e recomeça a cada período.</p></div><div className="period-toggle"><button className={period === 'dia' ? 'active' : ''} onClick={() => setPeriod('dia')}>Hoje</button><button className={period === 'semana' ? 'active' : ''} onClick={() => setPeriod('semana')}>Semana</button></div></section><div className="ranking-list">{ranking.map((item, index) => <article key={item.profile.id} className={index === 0 ? 'winner' : ''}><strong>{index + 1}</strong><span className="player-avatar" style={{ background: item.profile.avatarColor }}>{item.profile.displayName.slice(0, 1)}</span><div><h3>{item.profile.displayName}</h3><p>{item.profile.trophies} troféus · nível {Math.floor(item.profile.workspaceXp / 100) + 1}</p></div><span><Trophy size={17} />{item.points} XP</span></article>)}</div><section className="bonus-rules"><h3>Como os bônus funcionam</h3><div><span><ListChecks />Tarefa<strong>10–30 XP</strong></span><span><Goal />Meta completa<strong>XP configurado + troféu</strong></span><span><Medal />Foco principal<strong>30 XP por tarefa</strong></span></div><p>Uma mesma entrega só pontua uma vez, mesmo que seja reaberta.</p></section></div> }
function TeamMembers({ state, profiles, inviteCode, notify }: { state: TeamState; profiles: TeamState['profiles']; inviteCode: string; notify: (text: string) => void }) { return <div className="team-content"><section className="invite-panel"><div><UserRoundPlus size={22} /><div><p className="eyebrow">CONVIDAR COM SEGURANÇA</p><h2>Código do workspace</h2><p>Seu sócio cria a conta e usa este código uma vez.</p></div></div><button onClick={() => copyInvite(inviteCode, notify)}><strong>{inviteCode}</strong><Copy size={16} /></button></section><div className="member-grid">{profiles.map((profile) => { const member = state.members.find((item) => item.userId === profile.id); const completed = state.activities.filter((item) => item.userId === profile.id && item.type === 'task').length; return <article key={profile.id}><div className="member-cover" style={{ '--player': profile.avatarColor } as React.CSSProperties} /><span className="member-avatar" style={{ background: profile.avatarColor }}>{profile.displayName.slice(0, 1)}</span><small>{member?.role === 'owner' ? 'Fundador' : 'Membro'}</small><h2>{profile.displayName}</h2><p><Trophy size={15} />{profile.trophies} troféus <Coins size={15} />{profile.workspaceXp} XP</p><div><span><strong>{completed}</strong> entregas</span><span><strong>{Math.floor(profile.workspaceXp / 100) + 1}</strong> nível</span></div></article> })}</div><section className="privacy-note"><ShieldCheck size={20} /><div><strong>O workspace vê trabalho, não a vida inteira.</strong><p>Energia, rotina, medicação e hábitos privados continuam no painel individual.</p></div></section></div> }

function GoalDialog({ state, actions, item, initialProjectId, close, notify }: { state: TeamState; actions: TeamActions; item?: TeamGoal; initialProjectId?: string; close: () => void; notify: (text: string) => void }) {
  const [title, setTitle] = useState(item?.title ?? ''); const [description, setDescription] = useState(item?.description ?? ''); const [projectId, setProject] = useState(item?.projectId ?? initialProjectId ?? ''); const [depends, setDepends] = useState(item?.dependsOnGoalId ?? ''); const [ownerId, setOwner] = useState(item?.ownerId ?? ''); const [deadline, setDeadline] = useState(item?.deadline ?? ''); const [priority, setPriority] = useState<TeamPriority>(item?.priority ?? 'importante'); const [status, setStatus] = useState<GoalStatus>(item?.status ?? 'planejada'); const [rewardXp, setReward] = useState(item?.rewardXp ?? 90)
  async function submit(event: React.FormEvent) { event.preventDefault(); if (title.trim().length < 3) return; try { await actions.saveGoal({ title, description, projectId: projectId || undefined, dependsOnGoalId: depends || undefined, ownerId: ownerId || undefined, deadline: deadline || undefined, priority, status, rewardXp, metric: 'etapas', target: item?.target ?? 1 }, item?.id); notify(item ? 'Meta atualizada.' : 'Meta criada.'); close() } catch { notify('Não foi possível salvar a meta.') } }
  return <Modal title={item ? 'Editar meta' : 'Nova meta'} close={close}><form onSubmit={submit}><label>Meta<input autoFocus value={title} onChange={(e) => setTitle(e.target.value)} /></label><label>Resultado esperado<textarea rows={3} value={description} onChange={(e) => setDescription(e.target.value)} /></label><div className="form-grid"><label>Operação<select value={projectId} onChange={(e) => setProject(e.target.value)}><option value="">Sem vínculo</option>{state.projects.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Prioridade<select value={priority} onChange={(e) => setPriority(e.target.value as TeamPriority)}><option value="urgente">Foco principal</option><option value="importante">Alta</option><option value="normal">Normal</option></select></label></div><div className="form-grid"><label>Status<select value={status} onChange={(e) => setStatus(e.target.value as GoalStatus)}>{Object.entries(goalStatusLabels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label>Prazo opcional<input type="date" value={deadline} onChange={(e) => setDeadline(e.target.value)} /></label></div><div className="form-grid"><label>Depende de<select value={depends} onChange={(e) => setDepends(e.target.value)}><option value="">Nada</option>{state.goals.filter((g) => g.id !== item?.id).map((g) => <option key={g.id} value={g.id}>{g.title}</option>)}</select></label><label>Responsável<select value={ownerId} onChange={(e) => setOwner(e.target.value)}><option value="">A dupla</option>{state.profiles.map((p) => <option key={p.id} value={p.id}>{p.displayName}</option>)}</select></label></div><label>Bônus<select value={rewardXp} onChange={(e) => setReward(Number(e.target.value))}><option value="60">60 XP + troféu</option><option value="90">90 XP + troféu</option><option value="120">120 XP + troféu</option></select></label><DialogFooter item={item} onDelete={() => confirmDelete('esta meta e suas tarefas', async () => { await actions.deleteGoal(item!.id); close() }, notify)} submitLabel={item ? 'Salvar alterações' : 'Criar meta'} disabled={title.trim().length < 3} close={close} /></form></Modal>
}

function TaskDialog({ state, actions, item, initialGoalId, close, notify }: { state: TeamState; actions: TeamActions; item?: TeamTask; initialGoalId?: string; close: () => void; notify: (text: string) => void }) {
  const [title, setTitle] = useState(item?.title ?? ''); const [description, setDescription] = useState(item?.description ?? ''); const [goalId, setGoal] = useState(item?.goalId ?? initialGoalId ?? ''); const initialProject = item?.projectId ?? state.goals.find((g) => g.id === initialGoalId)?.projectId ?? ''; const [projectId, setProject] = useState(initialProject); const [depends, setDepends] = useState(item?.dependsOnTaskId ?? ''); const [area, setArea] = useState<TeamArea>(item?.area ?? 'operacao'); const [priority, setPriority] = useState<TeamPriority>(item?.priority ?? 'importante'); const [assigneeId, setAssignee] = useState(item?.assigneeId ?? ''); const [dueDate, setDueDate] = useState(item?.dueDate ?? ''); const [status, setStatus] = useState<TeamTaskStatus>(item?.status ?? 'backlog'); const [waitingUntil, setWaitingUntil] = useState(toDateTimeInput(item?.waitingUntil))
  const candidates = state.tasks.filter((t) => t.id !== item?.id && (!goalId || t.goalId === goalId)); const points = pointsForPriority(priority)
  async function submit(event: React.FormEvent) { event.preventDefault(); if (title.trim().length < 3 || (status === 'aguardando' && !waitingUntil)) return; try { await actions.saveTask({ title, description, goalId: goalId || undefined, projectId: projectId || undefined, dependsOnTaskId: depends || undefined, area, priority, assigneeId: assigneeId || undefined, dueDate: dueDate || undefined, waitingUntil: status === 'aguardando' && waitingUntil ? new Date(waitingUntil).toISOString() : undefined, status }, item?.id); notify(item ? 'Tarefa atualizada.' : 'Tarefa criada.'); close() } catch { notify('Não foi possível salvar a tarefa.') } }
  return <Modal title={item ? 'Editar tarefa' : 'Nova tarefa'} close={close}><form onSubmit={submit}><label>Próximo passo<input autoFocus value={title} onChange={(e) => setTitle(e.target.value)} /></label><label>Definição de pronto<textarea rows={2} value={description} onChange={(e) => setDescription(e.target.value)} /></label><div className="form-grid"><label>Meta<select value={goalId} onChange={(e) => { setGoal(e.target.value); const goal = state.goals.find((g) => g.id === e.target.value); if (goal?.projectId) setProject(goal.projectId) }}><option value="">Sem meta</option>{state.goals.map((g) => <option key={g.id} value={g.id}>{g.title}</option>)}</select></label><label>Operação<select value={projectId} onChange={(e) => setProject(e.target.value)}><option value="">Geral</option>{state.projects.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><div className="form-grid"><label>Responsável<select value={assigneeId} onChange={(e) => setAssignee(e.target.value)}><option value="">Quem concluir</option>{state.profiles.map((p) => <option key={p.id} value={p.id}>{p.displayName}</option>)}</select></label><label>Depende de<select value={depends} onChange={(e) => setDepends(e.target.value)}><option value="">Nada</option>{candidates.map((t) => <option key={t.id} value={t.id}>{t.title}</option>)}</select></label></div><div className="form-grid three"><label>Área<select value={area} onChange={(e) => setArea(e.target.value as TeamArea)}>{Object.entries(areaLabels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label>Prioridade<select value={priority} onChange={(e) => setPriority(e.target.value as TeamPriority)}><option value="urgente">Foco · 30 XP</option><option value="importante">Alta · 20 XP</option><option value="normal">Normal · 10 XP</option></select></label><label>Status<select value={status} onChange={(e) => setStatus(e.target.value as TeamTaskStatus)}>{statuses.map((s) => <option key={s.id} value={s.id}>{s.label}</option>)}</select></label></div>{status === 'aguardando' && <label className="waiting-field">Aguardar até<input required type="datetime-local" value={waitingUntil} onChange={(e) => setWaitingUntil(e.target.value)} /><small>Exemplo: marque 24 horas à frente. O sistema mostrará a contagem regressiva.</small></label>}<label>Prazo opcional<input type="date" value={dueDate} onChange={(e) => setDueDate(e.target.value)} /></label><DialogFooter item={item} onDelete={() => confirmDelete('esta tarefa', async () => { await actions.deleteTask(item!.id); close() }, notify)} submitLabel={`${item ? 'Salvar' : 'Criar'} · ${points} XP`} disabled={title.trim().length < 3 || (status === 'aguardando' && !waitingUntil)} close={close} /></form></Modal>
}

function ProjectDialog({ actions, item, close, notify }: { actions: TeamActions; item?: TeamProject; close: () => void; notify: (text: string) => void }) { const [name, setName] = useState(item?.name ?? ''); const [summary, setSummary] = useState(item?.summary ?? ''); const [color, setColor] = useState(item?.color ?? '#77a784'); const [priority, setPriority] = useState<TeamPriority>(item?.priority ?? 'importante'); const [status, setStatus] = useState<TeamProject['status']>(item?.status ?? 'ativo'); async function submit(e: React.FormEvent) { e.preventDefault(); try { await actions.saveProject({ name, summary, color, priority, status }, item?.id); notify(item ? 'Operação atualizada.' : 'Operação criada.'); close() } catch { notify('Não foi possível salvar a operação.') } } return <Modal title={item ? 'Editar operação' : 'Nova operação'} close={close}><form onSubmit={submit}><label>Nome<input autoFocus value={name} onChange={(e) => setName(e.target.value)} /></label><label>Resultado esperado<textarea rows={3} value={summary} onChange={(e) => setSummary(e.target.value)} /></label><div className="form-grid"><label>Prioridade<select value={priority} onChange={(e) => setPriority(e.target.value as TeamPriority)}><option value="urgente">Foco principal</option><option value="importante">Alta</option><option value="normal">Normal</option></select></label><label>Status<select value={status} onChange={(e) => setStatus(e.target.value as TeamProject['status'])}><option value="ativo">Ativa</option><option value="pausado">Pausada</option><option value="concluido">Concluída</option></select></label></div><label>Cor<input type="color" value={color} onChange={(e) => setColor(e.target.value)} /></label><DialogFooter item={item} onDelete={() => confirmDelete('esta operação (as metas serão mantidas sem vínculo)', async () => { await actions.deleteProject(item!.id); close() }, notify)} submitLabel={item ? 'Salvar alterações' : 'Criar operação'} disabled={name.trim().length < 2} close={close} /></form></Modal> }
function IdeaDialog({ actions, item, close, notify }: { actions: TeamActions; item?: TeamIdea; close: () => void; notify: (text: string) => void }) { const [title, setTitle] = useState(item?.title ?? ''); const [notes, setNotes] = useState(item?.notes ?? ''); const [priority, setPriority] = useState<TeamPriority>(item?.priority ?? 'normal'); const [status, setStatus] = useState<IdeaStatus>(item?.status ?? 'inbox'); async function submit(e: React.FormEvent) { e.preventDefault(); try { await actions.saveIdea({ title, notes, priority, status }, item?.id); notify(item ? 'Ideia atualizada.' : 'Ideia registrada.'); close() } catch { notify('Não foi possível salvar a ideia.') } } return <Modal title={item ? 'Editar ideia' : 'Nova ideia'} close={close}><form onSubmit={submit}><label>Ideia<input autoFocus value={title} onChange={(e) => setTitle(e.target.value)} /></label><label>Observações<textarea rows={4} value={notes} onChange={(e) => setNotes(e.target.value)} /></label><div className="form-grid"><label>Prioridade<select value={priority} onChange={(e) => setPriority(e.target.value as TeamPriority)}><option value="urgente">Foco principal</option><option value="importante">Alta</option><option value="normal">Normal</option></select></label><label>Status<select value={status} onChange={(e) => setStatus(e.target.value as IdeaStatus)}><option value="inbox">Caixa de entrada</option><option value="avaliando">Avaliando</option><option value="aprovada">Aprovada</option><option value="arquivada">Arquivada</option></select></label></div><DialogFooter item={item} onDelete={() => confirmDelete('esta ideia', async () => { await actions.deleteIdea(item!.id); close() }, notify)} submitLabel={item ? 'Salvar alterações' : 'Registrar ideia'} disabled={title.trim().length < 2} close={close} /></form></Modal> }

function TeamGate({ openAccount }: { openAccount: () => void }) { return <div className="page inner-page"><section className="team-gate"><span><Users size={30} /></span><p className="eyebrow">CONTA NECESSÁRIA</p><h1>Entre para trabalhar em dupla.</h1><p>Seu painel pessoal continua privado. A conta conecta apenas os workspaces compartilhados.</p><button className="primary-button" onClick={openAccount}>Entrar ou criar conta <ArrowRight size={16} /></button></section></div> }
function EmptyWorkspace({ actions }: { actions: TeamActions }) { const [name, setName] = useState('Metas Business'); const [code, setCode] = useState(''); return <div className="page inner-page"><section className="page-heading"><div><p className="eyebrow">PRIMEIRO WORKSPACE</p><h1>Crie a base da operação.</h1><p>Ou entre com o código que seu sócio enviou.</p></div></section><div className="workspace-onboarding"><section className="surface"><Crown /><h2>Criar workspace</h2><input value={name} onChange={(e) => setName(e.target.value)} /><button className="primary-button" disabled={name.trim().length < 2} onClick={() => actions.createWorkspace(name)}>Criar espaço</button></section><section className="surface"><UserRoundPlus /><h2>Entrar com convite</h2><input value={code} onChange={(e) => setCode(e.target.value.toUpperCase())} /><button className="secondary-button" disabled={code.trim().length < 4} onClick={() => actions.joinWorkspace(code)}>Entrar</button></section></div></div> }
function DialogFooter({ item, onDelete, submitLabel, disabled, close }: { item?: unknown; onDelete: () => void; submitLabel: string; disabled: boolean; close: () => void }) { return <footer className="dialog-actions">{Boolean(item) && <button type="button" className="danger-button" onClick={onDelete}><Trash2 size={15} />Excluir</button>}<span /><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button" disabled={disabled}>{submitLabel}</button></footer> }
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="dialog-layer" onMouseDown={(e) => { if (e.target === e.currentTarget) close() }}><section className="dialog" role="dialog" aria-modal="true" aria-label={title}><header><div><p className="eyebrow">METAS BUSINESS</p><h2>{title}</h2></div><button className="icon-button" onClick={close} aria-label="Fechar"><X size={18} /></button></header>{children}</section></div> }
function Empty({ title, text, action, onAction }: { title: string; text: string; action?: string; onAction?: () => void }) { return <div className="empty-state"><Lightbulb size={22} /><h3>{title}</h3><p>{text}</p>{action && <button className="quiet-button" onClick={onAction}><Plus size={14} />{action}</button>}</div> }
function PlayerAvatar({ state, id }: { state: TeamState; id?: string }) { const player = state.profiles.find((item) => item.id === id); return <span className="player-avatar small" style={{ background: player?.avatarColor }}>{player?.displayName.slice(0, 1) ?? '?'}</span> }
function formatDate(date: string) { return new Date(`${date}T12:00:00`).toLocaleDateString('pt-BR') }
function formatDateTime(date: string) { return new Date(date).toLocaleString('pt-BR', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }) }
function toDateTimeInput(date?: string) { if (!date) return ''; const value = new Date(date); const local = new Date(value.getTime() - value.getTimezoneOffset() * 60_000); return local.toISOString().slice(0, 16) }
function formatRemaining(milliseconds: number) { const minutes = Math.max(0, Math.ceil(milliseconds / 60_000)); const hours = Math.floor(minutes / 60); const rest = minutes % 60; return hours ? `${hours}h ${rest}min` : `${rest}min` }
function copyInvite(code: string, notify: (text: string) => void) { navigator.clipboard?.writeText(code); notify(`Código ${code} copiado.`) }
async function confirmDelete(label: string, action: () => Promise<void> | void, notify: (text: string) => void) { if (!window.confirm(`Excluir ${label}? Esta ação não pode ser desfeita.`)) return; try { await action(); notify('Item excluído.') } catch { notify('Não foi possível excluir.') } }
