import { useState } from 'react'
import { Activity, ArrowRight, BarChart3, BriefcaseBusiness, Check, ChevronRight, ClipboardList, Coins, Copy, Crown, FolderKanban, Goal, Plus, ShieldCheck, Trophy, UserRoundPlus, Users, X } from 'lucide-react'
import { localDate } from '../lib/store'
import { pointsForPriority, workspaceRanking } from '../lib/teamStats'
import type { TeamActions } from '../hooks/useTeamState'
import type { TeamArea, TeamPriority, TeamState, TeamTask, TeamTaskStatus } from '../types/team'

type TeamTab = 'visao' | 'quadro' | 'projetos' | 'ranking' | 'equipe'
const statuses: { id: TeamTaskStatus; label: string }[] = [
  { id: 'backlog', label: 'Caixa de entrada' }, { id: 'hoje', label: 'Hoje' }, { id: 'andamento', label: 'Em andamento' }, { id: 'revisao', label: 'Revisão' }, { id: 'concluida', label: 'Concluídas' },
]
const areaLabels: Record<TeamArea, string> = { trafego: 'Tráfego', sites: 'Sites', campanhas: 'Campanhas', clientes: 'Clientes', vsl: 'VSL', operacao: 'Operação', geral: 'Geral' }

export function TeamPage({ state, actions, openAccount, notify }: { state: TeamState; actions: TeamActions; openAccount: () => void; notify: (text: string) => void }) {
  const [tab, setTab] = useState<TeamTab>('visao')
  const [dialog, setDialog] = useState<'task' | 'project' | 'goal' | null>(null)
  const active = state.workspaces.find((item) => item.id === state.activeWorkspaceId)
  if (state.configured && !state.user) return <TeamGate openAccount={openAccount} />
  if (state.loading) return <div className="page inner-page"><div className="team-loading"><Activity className="spin" /><h2>Sincronizando a operação...</h2><p>Buscando tarefas, jogadores e placar.</p></div></div>
  if (!active) return <EmptyWorkspace actions={actions} />
  const memberProfiles = state.profiles.filter((profile) => state.members.some((member) => member.workspaceId === active.id && member.userId === profile.id))
  const todayDone = state.tasks.filter((task) => task.status === 'concluida' && task.completedAt?.slice(0, 10) === localDate()).length
  return <div className="page inner-page team-page">
    <section className="team-hero">
      <div><p className="eyebrow">WORKSPACE COMPARTILHADO</p><div className="workspace-title"><span><BriefcaseBusiness size={22} /></span><div><h1>{active.name}</h1><p>{active.description}</p></div></div></div>
      <div className="workspace-actions"><span className={`sync-state ${state.mode}`}><i />{state.mode === 'cloud' ? 'Sincronizado' : 'Demonstração local'}</span><button className="secondary-button" onClick={() => { navigator.clipboard?.writeText(active.inviteCode); notify(`Código ${active.inviteCode} copiado.`) }}><Copy size={15} />Convidar sócio</button><button className="primary-button" onClick={() => setDialog('task')}><Plus size={16} />Nova tarefa</button></div>
    </section>
    {state.error && <div className="inline-error">{state.error}</div>}
    <div className="team-tabs" role="tablist">{([
      ['visao', BarChart3, 'Visão geral'], ['quadro', ClipboardList, 'Quadro'], ['projetos', FolderKanban, 'Projetos'], ['ranking', Trophy, 'Ranking'], ['equipe', Users, 'Equipe'],
    ] as const).map(([id, Icon, label]) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}><Icon size={16} />{label}</button>)}</div>
    {tab === 'visao' && <TeamOverview state={state} memberProfiles={memberProfiles} todayDone={todayDone} setTab={setTab} openTask={() => setDialog('task')} />}
    {tab === 'quadro' && <TeamBoard state={state} actions={actions} />}
    {tab === 'projetos' && <TeamProjects state={state} actions={actions} openProject={() => setDialog('project')} openGoal={() => setDialog('goal')} />}
    {tab === 'ranking' && <TeamRanking state={state} profiles={memberProfiles} />}
    {tab === 'equipe' && <TeamMembers state={state} profiles={memberProfiles} inviteCode={active.inviteCode} notify={notify} />}
    {dialog === 'task' && <TaskDialog state={state} actions={actions} close={() => setDialog(null)} notify={notify} />}
    {dialog === 'project' && <ProjectDialog actions={actions} close={() => setDialog(null)} notify={notify} />}
    {dialog === 'goal' && <GoalDialog actions={actions} close={() => setDialog(null)} notify={notify} />}
  </div>
}

function TeamGate({ openAccount }: { openAccount: () => void }) {
  return <div className="page inner-page"><section className="team-gate"><span><Users size={30} /></span><p className="eyebrow">CONTA NECESSÁRIA</p><h1>Entre para trabalhar em dupla.</h1><p>Seu painel pessoal continua privado. A conta conecta apenas os workspaces que você escolher compartilhar.</p><button className="primary-button" onClick={openAccount}>Entrar ou criar conta <ArrowRight size={16} /></button></section></div>
}

function EmptyWorkspace({ actions }: { actions: TeamActions }) {
  const [name, setName] = useState('Metas Business'); const [code, setCode] = useState('')
  return <div className="page inner-page"><section className="page-heading"><div><p className="eyebrow">PRIMEIRO WORKSPACE</p><h1>Crie a base da operação.</h1><p>Ou entre com o código que seu sócio enviou.</p></div></section><div className="workspace-onboarding"><section className="surface"><Crown size={23} /><h2>Criar workspace</h2><p>Você será o dono e poderá compartilhar o código.</p><input value={name} onChange={(event) => setName(event.target.value)} /><button className="primary-button" disabled={name.trim().length < 2} onClick={() => actions.createWorkspace(name)}>Criar espaço</button></section><section className="surface"><UserRoundPlus size={23} /><h2>Entrar com convite</h2><p>Cole o código recebido. Sua conta entrará como membro.</p><input value={code} onChange={(event) => setCode(event.target.value.toUpperCase())} placeholder="EX.: A1B2C3D4" /><button className="secondary-button" disabled={code.trim().length < 4} onClick={() => actions.joinWorkspace(code)}>Entrar no workspace</button></section></div></div>
}

function TeamOverview({ state, memberProfiles, todayDone, setTab, openTask }: { state: TeamState; memberProfiles: TeamState['profiles']; todayDone: number; setTab: (tab: TeamTab) => void; openTask: () => void }) {
  const today = state.tasks.filter((item) => item.dueDate === localDate() && item.status !== 'concluida')
  const urgent = today.filter((item) => item.priority === 'urgente').length
  return <div className="team-content"><div className="team-metrics"><article><span><Check size={18} /></span><div><strong>{todayDone}</strong><small>entregas hoje</small></div></article><article><span><ClipboardList size={18} /></span><div><strong>{today.length}</strong><small>em aberto hoje</small></div></article><article><span><Activity size={18} /></span><div><strong>{urgent}</strong><small>urgências reais</small></div></article><article><span><Users size={18} /></span><div><strong>{memberProfiles.length}</strong><small>jogadores ativos</small></div></article></div>
    <div className="team-overview-grid"><section className="surface operation-now"><div className="section-title"><div><p className="eyebrow">OPERAÇÃO AGORA</p><h2>O que precisa ficar palpável</h2></div><button className="quiet-button" onClick={openTask}><Plus size={15} />Adicionar</button></div>{today.length ? today.slice(0, 5).map((task) => <TaskRow key={task.id} task={task} state={state} onOpen={() => setTab('quadro')} />) : <div className="empty-compact"><p>Nenhuma tarefa aberta para hoje. Espaço livre também é capacidade.</p></div>}<button className="text-link" onClick={() => setTab('quadro')}>Abrir quadro completo <ChevronRight size={14} /></button></section>
      <section className="surface duo-pulse"><div className="section-title compact"><div><p className="eyebrow">DUPLA EM MOVIMENTO</p><h2>Jogadores</h2></div><Trophy size={20} /></div>{memberProfiles.map((profile) => <PlayerLine key={profile.id} profile={profile} activities={state.activities} />)}</section></div>
    <section className="shared-goals"><div className="section-title"><div><p className="eyebrow">OBJETIVOS DA OPERAÇÃO</p><h2>Direção compartilhada</h2></div></div><div>{state.goals.map((goal) => { const progress = Math.min(100, Math.round(goal.current / goal.target * 100)); return <article key={goal.id}><span><Goal size={18} /></span><div><h3>{goal.title}</h3><p>{goal.current} de {goal.target} {goal.metric}</p><div className="soft-progress"><i style={{ width: `${progress}%` }} /></div></div><strong>{progress}%</strong></article> })}</div></section>
  </div>
}

function TeamBoard({ state, actions }: { state: TeamState; actions: TeamActions }) {
  return <div className="kanban-board">{statuses.map((column) => { const items = state.tasks.filter((item) => item.status === column.id); return <section className="kanban-column" key={column.id}><header><span>{column.label}</span><i>{items.length}</i></header><div>{items.map((task) => <article className={`team-task priority-${task.priority}`} key={task.id}><div><span className="area-chip">{areaLabels[task.area]}</span><strong>{task.points} XP</strong></div><h3>{task.title}</h3><p>{task.description}</p><footer><PlayerAvatar state={state} id={task.assigneeId} /><select aria-label={`Mover ${task.title}`} value={task.status} onChange={(event) => actions.moveTask(task.id, event.target.value as TeamTaskStatus)}>{statuses.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></footer></article>)}</div></section> })}</div>
}

function TeamProjects({ state, actions, openProject, openGoal }: { state: TeamState; actions: TeamActions; openProject: () => void; openGoal: () => void }) {
  return <div className="team-content"><section className="section-title"><div><p className="eyebrow">FRENTES DE TRABALHO</p><h2>Projetos do workspace</h2></div><button className="primary-button" onClick={openProject}><Plus size={15} />Novo projeto</button></section><div className="team-project-grid">{state.projects.map((project) => { const tasks = state.tasks.filter((item) => item.projectId === project.id); const done = tasks.filter((item) => item.status === 'concluida').length; const progress = tasks.length ? Math.round(done / tasks.length * 100) : 0; return <article key={project.id} style={{ '--project': project.color } as React.CSSProperties}><span><FolderKanban /></span><small>{project.status}</small><h2>{project.name}</h2><p>{project.summary}</p><div className="soft-progress"><i style={{ width: `${progress}%` }} /></div><footer><span>{done}/{tasks.length} entregas</span><strong>{progress}%</strong></footer></article> })}</div><section className="surface shared-goal-list"><div className="section-title"><div><p className="eyebrow">PLACAR DE OBJETIVOS</p><h2>Metas do negócio</h2></div><button className="quiet-button" onClick={openGoal}><Plus size={15} />Novo objetivo</button></div>{state.goals.length ? state.goals.map((goal) => <article key={goal.id}><div><strong>{goal.title}</strong><small>{goal.current}/{goal.target} {goal.metric} · +{goal.rewardXp} XP</small></div><button disabled={goal.completed} onClick={() => actions.advanceGoal(goal.id)}>{goal.completed ? 'Concluído' : '+ Registrar avanço'}</button></article>) : <div className="empty-compact"><p>Nenhum objetivo compartilhado ainda.</p></div>}</section></div>
}

function TeamRanking({ state, profiles }: { state: TeamState; profiles: TeamState['profiles'] }) {
  const [period, setPeriod] = useState<'dia' | 'semana'>('semana')
  const ranking = workspaceRanking(profiles, state.activities, period === 'dia' ? 1 : 7)
  return <div className="team-content"><section className="ranking-hero"><div><p className="eyebrow">COMPETIÇÃO LEVE</p><h2>Ranking da dupla</h2><p>O placar celebra entregas; não mede valor pessoal e zera a cada período.</p></div><div className="period-toggle"><button className={period === 'dia' ? 'active' : ''} onClick={() => setPeriod('dia')}>Hoje</button><button className={period === 'semana' ? 'active' : ''} onClick={() => setPeriod('semana')}>Semana</button></div></section><div className="ranking-list">{ranking.map((item, index) => <article key={item.profile.id} className={index === 0 ? 'winner' : ''}><strong>{index + 1}</strong><span className="player-avatar" style={{ background: item.profile.avatarColor }}>{item.profile.displayName.slice(0, 1)}</span><div><h3>{item.profile.displayName}</h3><p>{item.profile.trophies} troféus · nível {Math.floor(item.profile.workspaceXp / 100) + 1}</p></div><span><Trophy size={17} />{item.points} XP</span></article>)}</div></div>
}

function TeamMembers({ state, profiles, inviteCode, notify }: { state: TeamState; profiles: TeamState['profiles']; inviteCode: string; notify: (text: string) => void }) {
  return <div className="team-content"><section className="invite-panel"><div><UserRoundPlus size={22} /><div><p className="eyebrow">CONVIDAR COM SEGURANÇA</p><h2>Código do workspace</h2><p>Seu sócio cria a conta e usa este código uma vez.</p></div></div><button onClick={() => { navigator.clipboard?.writeText(inviteCode); notify('Código copiado.') }}><strong>{inviteCode}</strong><Copy size={16} /></button></section><div className="member-grid">{profiles.map((profile) => { const member = state.members.find((item) => item.userId === profile.id); const completed = state.activities.filter((item) => item.userId === profile.id && item.type === 'task').length; return <article key={profile.id}><div className="member-cover" style={{ '--player': profile.avatarColor } as React.CSSProperties} /><span className="member-avatar" style={{ background: profile.avatarColor }}>{profile.displayName.slice(0, 1)}</span><small>{member?.role === 'owner' ? 'Fundador' : 'Membro'}</small><h2>{profile.displayName}</h2><p><Trophy size={15} />{profile.trophies} troféus <Coins size={15} />{profile.workspaceXp} XP</p><div><span><strong>{completed}</strong> entregas</span><span><strong>{Math.floor(profile.workspaceXp / 100) + 1}</strong> nível</span></div></article> })}</div><section className="privacy-note"><ShieldCheck size={20} /><div><strong>O workspace vê trabalho, não a vida inteira.</strong><p>Energia, rotina e hábitos privados continuam no painel individual. Só aparece aqui o que a pessoa compartilha conscientemente.</p></div></section></div>
}

function TaskDialog({ state, actions, close, notify }: { state: TeamState; actions: TeamActions; close: () => void; notify: (text: string) => void }) {
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [area, setArea] = useState<TeamArea>('operacao'); const [priority, setPriority] = useState<TeamPriority>('importante'); const [assigneeId, setAssignee] = useState(state.user?.id ?? ''); const [projectId, setProject] = useState(''); const [dueDate, setDueDate] = useState(localDate())
  const points = pointsForPriority(priority)
  async function submit(event: React.FormEvent) { event.preventDefault(); if (title.trim().length < 3) return; await actions.addTask({ title: title.trim(), description: description.trim() || 'Entrega clara e verificável.', area, priority, assigneeId: assigneeId || undefined, projectId: projectId || undefined, dueDate, status: dueDate === localDate() ? 'hoje' : 'backlog', points }); notify('Tarefa adicionada ao quadro.'); close() }
  return <Modal title="Nova tarefa compartilhada" close={close}><form onSubmit={submit}><label>Entrega concreta<input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Ex.: republicar a página no domínio reserva" /></label><label>Definição de pronto<textarea rows={2} value={description} onChange={(event) => setDescription(event.target.value)} /></label><div className="form-grid"><label>Responsável<select value={assigneeId} onChange={(event) => setAssignee(event.target.value)}>{state.profiles.map((item) => <option value={item.id} key={item.id}>{item.displayName}</option>)}</select></label><label>Projeto<select value={projectId} onChange={(event) => setProject(event.target.value)}><option value="">Operação geral</option>{state.projects.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label></div><div className="form-grid three"><label>Área<select value={area} onChange={(event) => setArea(event.target.value as TeamArea)}>{Object.entries(areaLabels).map(([id, label]) => <option value={id} key={id}>{label}</option>)}</select></label><label>Prioridade<select value={priority} onChange={(event) => setPriority(event.target.value as TeamPriority)}><option value="urgente">Urgente · 30 XP</option><option value="importante">Importante · 20 XP</option><option value="normal">Normal · 10 XP</option></select></label><label>Prazo<input type="date" value={dueDate} onChange={(event) => setDueDate(event.target.value)} /></label></div><footer><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button" disabled={title.trim().length < 3}>Criar tarefa · {points} XP</button></footer></form></Modal>
}

function ProjectDialog({ actions, close, notify }: { actions: TeamActions; close: () => void; notify: (text: string) => void }) {
  const [name, setName] = useState(''); const [summary, setSummary] = useState(''); const [color, setColor] = useState('#77a7a4')
  async function submit(event: React.FormEvent) { event.preventDefault(); if (name.trim().length < 2) return; await actions.addProject({ name: name.trim(), summary: summary.trim(), color }); notify('Projeto compartilhado criado.'); close() }
  return <Modal title="Novo projeto do workspace" close={close}><form onSubmit={submit}><label>Nome<input autoFocus value={name} onChange={(event) => setName(event.target.value)} /></label><label>Resultado esperado<textarea value={summary} onChange={(event) => setSummary(event.target.value)} rows={3} /></label><label>Cor<input type="color" value={color} onChange={(event) => setColor(event.target.value)} /></label><footer><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button" disabled={name.trim().length < 2}>Criar projeto</button></footer></form></Modal>
}

function GoalDialog({ actions, close, notify }: { actions: TeamActions; close: () => void; notify: (text: string) => void }) {
  const [title, setTitle] = useState(''); const [metric, setMetric] = useState('entregas'); const [target, setTarget] = useState(10); const [deadline, setDeadline] = useState(localDate()); const [rewardXp, setRewardXp] = useState(100)
  async function submit(event: React.FormEvent) { event.preventDefault(); if (title.trim().length < 3) return; await actions.addGoal({ title: title.trim(), metric: metric.trim() || 'entregas', target: Math.max(1, target), deadline, rewardXp }); notify('Objetivo compartilhado criado.'); close() }
  return <Modal title="Novo objetivo do negócio" close={close}><form onSubmit={submit}><label>Resultado que queremos construir<input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} /></label><div className="form-grid"><label>Métrica<input value={metric} onChange={(event) => setMetric(event.target.value)} /></label><label>Quantidade<input type="number" min="1" value={target} onChange={(event) => setTarget(Number(event.target.value))} /></label></div><div className="form-grid"><label>Prazo<input type="date" value={deadline} onChange={(event) => setDeadline(event.target.value)} /></label><label>Prêmio<select value={rewardXp} onChange={(event) => setRewardXp(Number(event.target.value))}><option value="60">60 XP</option><option value="100">100 XP</option><option value="150">150 XP</option></select></label></div><footer><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button" disabled={title.trim().length < 3}>Criar objetivo</button></footer></form></Modal>
}

function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="dialog-layer"><section className="dialog" role="dialog" aria-modal="true" aria-label={title}><header><div><p className="eyebrow">METAS BUSINESS</p><h2>{title}</h2></div><button className="icon-button" onClick={close} aria-label="Fechar"><X size={18} /></button></header>{children}</section></div> }
function PlayerAvatar({ state, id }: { state: TeamState; id?: string }) { const player = state.profiles.find((item) => item.id === id); return <span className="player-avatar small" style={{ background: player?.avatarColor }}>{player?.displayName.slice(0, 1) ?? '?'}</span> }
function TaskRow({ task, state, onOpen }: { task: TeamTask; state: TeamState; onOpen: () => void }) { const player = state.profiles.find((item) => item.id === task.assigneeId); return <button className="operation-row" onClick={onOpen}><i className={task.priority} /><div><strong>{task.title}</strong><small>{areaLabels[task.area]} · {player?.displayName ?? 'Sem responsável'}</small></div><span>+{task.points} XP</span><ChevronRight size={15} /></button> }
function PlayerLine({ profile, activities }: { profile: TeamState['profiles'][number]; activities: TeamState['activities'] }) { const today = activities.filter((item) => item.userId === profile.id && item.date === localDate()).reduce((sum, item) => sum + item.points, 0); return <article className="player-line"><span className="player-avatar" style={{ background: profile.avatarColor }}>{profile.displayName.slice(0, 1)}</span><div><strong>{profile.displayName}</strong><small>{profile.trophies} troféus conquistados</small></div><span>+{today} hoje</span></article> }
