import { ArrowRight, BatteryFull, BatteryLow, BatteryMedium, Check, Clock3, Coins, FolderKanban, Plus, Search, Target, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { dayOffset, localDate } from '../lib/store'
import type { FocoActions } from '../hooks/useFocoState'
import type { AppState, Energy, Goal, Mission, PlanningTab, Project, RoutineBlock, View } from '../types'

function DialogShell({ title, eyebrow, close, children, small }: { title: string; eyebrow: string; close: () => void; children: React.ReactNode; small?: boolean }) {
  return <div className="dialog-layer" onMouseDown={(event) => event.target === event.currentTarget && close()}><section className={`dialog ${small ? 'small' : ''}`} role="dialog" aria-modal="true" aria-label={title}><header><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><button className="icon-button" onClick={close} aria-label="Fechar"><X size={19} /></button></header>{children}</section></div>
}

export function MissionDialog({ state, actions, close, notify, initialGoalId }: CommonProps & { initialGoalId?: string }) {
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [duration, setDuration] = useState(15); const [energy, setEnergy] = useState<Energy>('baixa'); const [priority, setPriority] = useState<Mission['priority']>('essencial'); const [dueDate, setDueDate] = useState(localDate()); const [projectId, setProjectId] = useState(''); const [goalId, setGoalId] = useState(initialGoalId ?? '')
  const valid = title.trim().length >= 3
  function submit(event: React.FormEvent) { event.preventDefault(); if (!valid) return; actions.addMission({ title: title.trim(), description: description.trim() || 'Comece pela menor ação visível.', duration, energy, priority, dueDate, projectId: projectId || undefined, goalId: goalId || undefined, completedAt: undefined }); notify(dueDate === localDate() ? 'Meta adicionada ao seu dia.' : 'Meta guardada para a data escolhida.'); close() }
  const reward = Math.max(10, Math.round(duration * 1.5))
  return <DialogShell title="Nova meta" eyebrow="PEQUENA, CLARA E POSSÍVEL" close={close}><form onSubmit={submit}><label>O que precisa ficar pronto?<input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Ex.: enviar a proposta revisada" /><small>Use um verbo que deixe claro quando terminou.</small></label><label>Qual é o primeiro passo? <span>opcional</span><textarea value={description} onChange={(event) => setDescription(event.target.value)} rows={2} placeholder="Ex.: abrir o documento e revisar apenas o título" /></label><div className="form-grid three"><label>Quando?<input type="date" value={dueDate} onChange={(event) => setDueDate(event.target.value)} /></label><label>Tempo<select value={duration} onChange={(event) => setDuration(Number(event.target.value))}>{[3,5,10,15,25,45,60].map((value) => <option key={value} value={value}>{value} minutos</option>)}</select></label><label>Importância<select value={priority} onChange={(event) => setPriority(event.target.value as Mission['priority'])}><option value="essencial">Essencial</option><option value="importante">Importante</option><option value="extra">Se der tempo</option></select></label></div><fieldset><legend>Energia necessária</legend><div className="energy-form">{([['baixa', BatteryLow, 'Leve'], ['media', BatteryMedium, 'Média'], ['alta', BatteryFull, 'Alta']] as const).map(([value, Icon, label]) => <button type="button" className={energy === value ? 'selected' : ''} key={value} onClick={() => setEnergy(value)}><Icon size={17} />{label}</button>)}</div></fieldset><div className="form-grid"><label>Projeto <span>opcional</span><select value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">Sem projeto</option>{state.projects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Objetivo <span>opcional</span><select value={goalId} onChange={(event) => setGoalId(event.target.value)}><option value="">Sem objetivo</option>{state.goals.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label></div><div className="form-reward"><Coins size={17} /><span>Ao concluir: <strong>+{reward} moedas</strong> e <strong>+{reward + 10} XP</strong></span></div><footer><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button" disabled={!valid}>Adicionar meta <ArrowRight size={16} /></button></footer></form></DialogShell>
}

export function ProjectDialog({ actions, close, notify }: Omit<CommonProps, 'state'>) {
  const [name, setName] = useState(''); const [why, setWhy] = useState(''); const [deadline, setDeadline] = useState(''); const [color, setColor] = useState('#86a873'); const colors = ['#86a873','#d9a76c','#77a7a4','#9c8fc7','#d4837d']
  function submit(event: React.FormEvent) { event.preventDefault(); if (name.trim().length < 2) return; actions.addProject({ name: name.trim(), why: why.trim() || 'Um projeto importante para mim.', deadline: deadline || undefined, color }); notify('Projeto criado. Agora escolha o primeiro marco.'); close() }
  return <DialogShell title="Novo projeto" eyebrow="DA IDEIA PARA A PRÓXIMA ENTREGA" close={close} small><form onSubmit={submit}><label>Nome do projeto<input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="Ex.: preparar meu portfólio" /></label><label>Por que isso importa?<textarea value={why} onChange={(event) => setWhy(event.target.value)} rows={3} placeholder="Uma frase para lembrar nos dias difíceis" /></label><label>Prazo de orientação <span>opcional</span><input type="date" value={deadline} onChange={(event) => setDeadline(event.target.value)} /></label><fieldset><legend>Cor de identificação</legend><div className="color-form">{colors.map((item) => <button type="button" key={item} className={color === item ? 'selected' : ''} onClick={() => setColor(item)} style={{ background: item }}>{color === item && <Check size={14} />}</button>)}</div></fieldset><footer><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button" disabled={name.trim().length < 2}>Criar projeto</button></footer></form></DialogShell>
}

export function GoalDialog({ actions, close, notify }: Omit<CommonProps, 'state'>) {
  const [title, setTitle] = useState(''); const [why, setWhy] = useState(''); const [area, setArea] = useState<Goal['area']>('pessoal'); const [target, setTarget] = useState(10); const [unit, setUnit] = useState('vezes'); const [deadline, setDeadline] = useState(dayOffset(30)); const [rewardCoins, setRewardCoins] = useState(100)
  function submit(event: React.FormEvent) { event.preventDefault(); if (title.trim().length < 3 || !deadline) return; actions.addGoal({ title: title.trim(), why: why.trim() || 'Quero construir isso aos poucos.', area, target: Math.max(1, target), unit: unit.trim() || 'vezes', deadline, rewardCoins }); notify('Objetivo criado. O primeiro avanço já pode ser pequeno.'); close() }
  return <DialogShell title="Novo objetivo" eyebrow="DIREÇÃO, NÃO COBRANÇA" close={close}><form onSubmit={submit}><label>O que você quer construir?<input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Ex.: praticar inglês com constância" /></label><label>Por que isso importa para você?<textarea value={why} onChange={(event) => setWhy(event.target.value)} rows={2} /></label><div className="form-grid"><label>Área<select value={area} onChange={(event) => setArea(event.target.value as Goal['area'])}><option value="pessoal">Pessoal</option><option value="saude">Saúde</option><option value="carreira">Carreira</option><option value="relacoes">Relações</option></select></label><label>Prazo<input required type="date" value={deadline} onChange={(event) => setDeadline(event.target.value)} /></label></div><div className="form-grid three"><label>Quantidade<input type="number" min="1" value={target} onChange={(event) => setTarget(Number(event.target.value))} /></label><label>Unidade<input value={unit} onChange={(event) => setUnit(event.target.value)} /></label><label>Recompensa<select value={rewardCoins} onChange={(event) => setRewardCoins(Number(event.target.value))}><option value="60">60 moedas</option><option value="100">100 moedas</option><option value="150">150 moedas</option></select></label></div><footer><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button" disabled={title.trim().length < 3 || !deadline}>Criar objetivo</button></footer></form></DialogShell>
}

export function RoutineDialog({ actions, close, notify }: Omit<CommonProps, 'state'>) {
  const [title, setTitle] = useState(''); const [start, setStart] = useState('09:00'); const [end, setEnd] = useState('09:30'); const [energy, setEnergy] = useState<Energy>('baixa'); const [weekdays, setWeekdays] = useState(true)
  function submit(event: React.FormEvent) { event.preventDefault(); if (title.trim().length < 2 || start >= end) return; const block: Omit<RoutineBlock, 'id' | 'completedDates'> = { title: title.trim(), start, end, energy, days: weekdays ? [1,2,3,4,5] : [0,1,2,3,4,5,6] }; actions.addRoutineBlock(block); notify('Bloco incluído na sua rotina.'); close() }
  return <DialogShell title="Novo bloco de rotina" eyebrow="UMA ÂNCORA, NÃO UMA GRADE" close={close} small><form onSubmit={submit}><label>Nome do bloco<input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Ex.: preparar o dia" /></label><div className="form-grid"><label>Começa<input type="time" value={start} onChange={(event) => setStart(event.target.value)} /></label><label>Termina<input type="time" value={end} onChange={(event) => setEnd(event.target.value)} /></label></div><label>Energia<select value={energy} onChange={(event) => setEnergy(event.target.value as Energy)}><option value="baixa">Leve</option><option value="media">Média</option><option value="alta">Alta</option></select></label><button type="button" className={`choice-row ${weekdays ? 'selected' : ''}`} onClick={() => setWeekdays(!weekdays)}><Check size={16} /><span><strong>{weekdays ? 'Segunda a sexta' : 'Todos os dias'}</strong><small>Clique para alternar</small></span></button>{start >= end && <p className="field-error">O horário final precisa ser posterior ao inicial.</p>}<footer><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button" disabled={title.trim().length < 2 || start >= end}>Adicionar bloco</button></footer></form></DialogShell>
}

export function MilestoneDialog({ project, actions, close, notify }: { project: Project; actions: FocoActions; close: () => void; notify: (text: string) => void }) {
  const [title, setTitle] = useState(''); function submit(event: React.FormEvent) { event.preventDefault(); if (!title.trim()) return; actions.addMilestone(project.id, title); notify('Marco adicionado ao projeto.'); close() }
  return <DialogShell title="Novo marco" eyebrow={project.name} close={close} small><form onSubmit={submit}><label>Qual entrega concreta mostra avanço?<input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Ex.: publicar a primeira versão" /><small>Precisa ser possível responder “sim, está pronto”.</small></label><footer><button type="button" className="secondary-button" onClick={close}>Cancelar</button><button className="primary-button" disabled={!title.trim()}><Plus size={16} />Adicionar marco</button></footer></form></DialogShell>
}

export function SearchDialog({ state, close, navigate, openPlanning }: { state: AppState; close: () => void; navigate: (view: View) => void; openPlanning: (tab: PlanningTab) => void }) {
  const [query, setQuery] = useState('')
  const results = useMemo(() => { const term = query.trim().toLocaleLowerCase('pt-BR'); if (!term) return []; return [
    ...state.missions.filter((item) => `${item.title} ${item.description}`.toLocaleLowerCase('pt-BR').includes(term)).map((item) => ({ id: item.id, icon: Clock3, title: item.title, type: 'Meta', action: () => navigate('hoje') })),
    ...state.projects.filter((item) => `${item.name} ${item.why}`.toLocaleLowerCase('pt-BR').includes(term)).map((item) => ({ id: item.id, icon: FolderKanban, title: item.name, type: 'Projeto', action: () => openPlanning('projetos') })),
    ...state.goals.filter((item) => `${item.title} ${item.why}`.toLocaleLowerCase('pt-BR').includes(term)).map((item) => ({ id: item.id, icon: Target, title: item.title, type: 'Objetivo', action: () => openPlanning('objetivos') })),
  ].slice(0, 8) }, [query, state, navigate, openPlanning])
  return <div className="dialog-layer search-layer" onMouseDown={(event) => event.target === event.currentTarget && close()}><section className="search-dialog" role="dialog" aria-modal="true" aria-label="Buscar"><div className="search-input"><Search size={20} /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar metas, projetos e objetivos..." /><button onClick={close}><X size={18} /></button></div><div className="search-results">{query && !results.length && <div className="empty-search"><Search size={23} /><p>Nada encontrado para “{query}”.</p></div>}{results.map(({ id, icon: Icon, title, type, action }) => <button key={id} onClick={() => { action(); close() }}><span><Icon size={17} /></span><div><strong>{title}</strong><small>{type}</small></div><ArrowRight size={15} /></button>)}{!query && <div className="search-hint"><p>Comece digitando algo que está na sua cabeça.</p><span><kbd>Esc</kbd> para fechar</span></div>}</div></section></div>
}

type CommonProps = { state: AppState; actions: FocoActions; close: () => void; notify: (text: string) => void }
